### ISSUE TITLE
Support non-ASCII changelog files

### ISSUE THREAD

**Issue by wosc** [zestsoftware/zest.releaser#109]
Before the Python-3 support came in, zest.releaser seemed to handle non-ASCII changelog files just fine (I never had any issues), but now I get this error:

```
  File "/home/wosc/install/zest/local/lib/python2.7/site-packages/zest.releaser-5.0-py2.7.egg/zest/releaser/prerelease.py", line 71, in execute
    self._write_history()
  File "/home/wosc/install/zest/local/lib/python2.7/site-packages/zest.releaser-5.0-py2.7.egg/zest/releaser/prerelease.py", line 161, in _write_history
    open(history, 'wb').write(contents)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 9914: ordinal not in range(128)
```

I've locally added `contents.encode('utf-8')` as a workaround, but I must confess, I'm not sure what a generic solution would look like -- and what the previous behaviour actually was (I'm guessing some kind of default encoding behaviour?).

**Comment by reinout** [comment]
If I remember correctly, there's a test somewhere that verifies that we can *read* a changelog with non-ascii characters. Shouldn't be too much effort to get my hands on a test that tests the writing back of the same file :-)

I'll see if I can fix it quickly. If it isn't fixed within two days, feel free to post a quick reminder here!

**Comment by mauritsvanrees** [comment]
I had the same issue recently which I fixed by editing the changelog. See https://github.com/plone/Products.TinyMCE/commit/4df527f8b9c7e2f76c57d343afb0a336d7b6f153

With zest.releaser 3.56 it worked fine. With 4.0 it fails with the UnicodeEncodeError.

Using `contents.encode('utf-8')` (in prerelease and postrelease) fixes it for Python 2.7, but then you get `TypeError: must be str, not bytes` on Python 3.

**Comment by mauritsvanrees** [comment]
I think I have fixed it in the above commit for Python 2 and 3.

**Comment by mauritsvanrees** [comment]
BTW, with the above fix, when I do a prerelease of Products.TinyMCE which has a weird and wrong and unnecessary non-ascii `s` in its changelog, I get this as one of the changes:

```
-  Fixeѕ https://dev.plone.org/ticket/10681
+  FixeŃ https://dev.plone.org/ticket/10681
```

and then for a postrelease:

```
-  FixeŃ https://dev.plone.org/ticket/10681
+  FixeĹÂ https://dev.plone.org/ticket/10681
```

With Python 3, I do not get any changes in that line.  So a bit weird on Python 2, but this changelog line is a bit weird anyway.

**Comment by mitchellrj** [comment]
Assuming that the file should be written with ```OUTPUT_ENCODING``` here isn't necessarily correct. Ideally it should be written with whatever encoding it was read with in the first place, which is not necessarily the same encoding as ```stdout``` is using. Generally it's safe to assume UTF-8, but there should be a way for users to specify their preferred encoding.

**Comment by mauritsvanrees** [comment]
Note: the original fix is already in version 5.1.

I have created pull request #116 with code that changes `utils.read_text_file` to return not only the text, but also the encoding that it used to read it.  I am using that encoding to write contents back, if needed.

Can you check if that is better?

Note that unfortunately, this has no effect (positive or negative) on what I get for TinyMCE a few comments up: the same small changes are written. `chardet` detects `ISO-8859-2` but seemingly isn't quite right. Well, that weird character is a typo anyway, so for that project it does not really matter.

**Comment by mauritsvanrees** [comment]
Merged. Closing.

**Comment by wosc** [comment]
I'm afraid I'm seeing the same issue in 5.1 still. I'll try and whip up an automated testcase.
