### ISSUE TITLE
Use twine and upload wheels

### ISSUE THREAD

**Issue by Natim** [zestsoftware/zest.releaser#119]
- We should use twine to upload packages securely in HTTPS
- We should upload bdist_wheel

See https://packaging.python.org/en/latest/distributing.html#upload-your-distributions

**Comment by reinout** [comment]
We already use twine (if it is available) :-) See http://zestreleaser.readthedocs.org/en/latest/uploading.html#uploading-with-twine

Wheels are also supported. See the documentation here: http://zestreleaser.readthedocs.org/en/latest/uploading.html#uploading-wheels

**Comment by Natim** [comment]
Thanks and sorry for the noise.
