### ISSUE TITLE
Setuptools-scm integration

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [zestsoftware/zest.releaser#121]
Setuptools-scm helps to generate version numbers based in scm metadata,

So the version bumping/dev versions mangleing is not needed when using it
Also any commit can get a own internal release

**Comment by reinout** [comment]
I've looked at https://pypi.python.org/pypi/setuptools_scm and I wonder how zest.releaser could be integrated (or the other way around). The goals seem to be different. 

I mean, normally with zest.releaser you'd "make a release" at a certain point. zest.releaser handles the version bumping and tagging and changelog beautification for you. If I read the documentation correctly, setuptools-scm "only" automatically detects that it is on the tag zest.releaser just tagged (and probably at least one commit after it) and increments the tag's version and reports it as a development one. (Just as zest.releaser does, only it hardcodes the answer in the setup.py).

The other way around, if you use setuptools-scm, you're tagging the software manually. So you probably already updated the changelog by hand? I mean, setuptools-scm only reports a non-development version if it is exactly ON the tag. So you cannot have zest.releaser use the not-yet-existing version of the not-yet-tagged software to update the changelog for you. At least, that's how I read the documentation :-)

So: I assume I'm missing something. Without knowing which version number to use, zest.releaser cannot update the changelog. And it cannot tag. And it isn't allowed to touch the version number. So nothing seems left :-)

**Comment by RonnyPfannschmidt** [comment]
bascially now that versions are automated for dev versions, and each version can have a internal release,
i want to work in the finer details around a release happening

which is bascially details like changelog maintenance, creating tags and so on

as for knowing which is the next version - its relatively easy to just ask setuptools_scm and strip off the .dev

one can also just mark the start of a new minor/major version via a tag, and would update the changelog accoringly

the integration direction would really be zest releaser using setuptools_scm  to handle version numbers in scm instead of files

**Comment by reinout** [comment]
So: zest.releaser should not touch the version information but get it from setuptools-scm? That would mean adding an extra method to `vcs.py`, see https://github.com/zestsoftware/zest.releaser/blob/master/zest/releaser/vcs.py#L62 . There are three different methods there for grabbing the version number, currently. The `get_setup_py_version()` would probably already work with setuptools-scm as-is as it asks calls setup.py with `--version`` :-)

It would then ask the user if the version it extracts (+1, just like your program does) is fine as the next release number. As a user, you can overwrite it. It then uses that version to tag and update the changelog and so.

But it, of course, also wants to *write* the version somewhere. So in https://github.com/zestsoftware/zest.releaser/blob/master/zest/releaser/vcs.py#L200 (`_update_version()`) it should be able to detect that it got the version number from setuptools-scm and leave it alone.

So: it sounds doable. But logically I'm not initially overjoyed by "just a few extra if/else statements". There are quite some extensions to zest.releaser that do just fine with just the entry point extention mechanism that we provide. This change would mean a change to the core. And a change I'm not initially sure of is right for zest.releaser.

So... how widely used is setuptools-scm? If there's no written-down version, it basically means that you have to have a network connection all the time just to determine the version. Or checkouts/clones instead of properly released packages.

**Comment by RonnyPfannschmidt** [comment]
adaption is slowly raising as i'm advocating it, i have no definitive users, but being part of pypa certainly helps the adaption

basically i want to use the surrounding logic of zest.releaser to do the pre-release and post-release logic as well as actual tagging, just not writing the versions to files

i'm mostly looking for guidance as to how to change/test/interact with zest.releaser in order to make it work together nicely

**Comment by reinout** [comment]
Well, the basic structure is that of the prerelease/release/postrelease step. The second structure is that of a base VCS class that's subclassed by git/hg/bzr/svn to provide the vcs-specific functionality.

So: everything is reasonably neatly done in an object oriented fashion. There's no API guarantee, but the internal structure hasn't changed often.

The most elegant way would be to use the entry points, but you could also do some experiments with subclassing the prerelease/postrelease steps.

**Comment by sean-abbott** [comment]
I'd like to +1 for this request.

**Comment by RonnyPfannschmidt** [comment]
as thing s look currently i'll eventually create a different tooling - somewhere in between zest and pbr

however before i get started that i#d like to have a discussion with @reinout

**Comment by sean-abbott** [comment]
I'm trying to figure out what I'm really looking for in a tool.  I think what I want is something very similar, but also branch name aware.  If the branch name is bugfix/** then we do a patch version, if it's feature/** we do a minor version, and if it's something a little less standard like major/** or apichange/** or something, we'd do a major version.  By being branch aware, the versioning from scm wouldn't need to worry about manually creating pre-release tags for non-patch versions.

**Comment by RonnyPfannschmidt** [comment]
sounds nice, please open a issue with a more complete description on setuptools_scm

**Comment by reinout** [comment]
I'm closing this (old) issue, feel free to reopen it if needed.

**Comment by hgrecco** [comment]
I have recently release 0.10 version of pint using setuptools-scm and zest.releaser. Briefly, I have created a `version.py` in the project root
```
# This is just for zest.releaser. Do not touch

__version__ = "0.11.dev0"
```

 and declare it in `setup.cfg`

```
[zest.releaser]
python-file-with-version = version.py
```

Finally, I just run the following command (to release 0.10)

```
SETUPTOOLS_SCM_PRETEND_VERSION=0.10 fullrelease
```

This works fine but it would be nice to find a way to avoid manually specifying the version. I think that I have found a way but I would need to know that a release process is running. Is there an environmental variable set by zest that I could use?

**Comment by reinout** [comment]
Environment variable? Not at the moment. Of course that's easy to add.

Easiest way for you to test things out is to just set the environment variable by hand (to pretend that zest.releaser set it) and run it.

See my first comment, though: I still don't really get the combination of zest.releaser and setuptools-scm :-) Zest.releaser is build to have a proper automated version + changelog nicely in versioned files. setuptools-scm seems build NOT to have that version in a versioned file. So they'll have to dance very carefully around each other somehow, it seems. 

Where do you use zest.releaser for? Updating the changelog? Then the changelog has the version number embedded. It then makes no sense (I guess) to explicitly not want to manage the version number itself in the same way. As I said: I might be missing something :-)

**Comment by hgrecco** [comment]
>  still don't really get the combination of zest.releaser and setuptools-scm 

In my workflow:
- zest.releaser manages the version number for the official releases (and helps with all the prerelease checks, tags, post release commits)
- setuptools-scm allows the developers and advanced users to install directly from git and have a different and sequential version for each commit `{next_version}.dev{distance}+{scm letter}{revision hash}`

Running both things was problematic for a couple of reasons
1. zest can read the version number but then it cannot write it back after bump it. That is why I needed to create `version.py`
2. setuptools-scm provides zest a  `{next_version}.dev{distance}+{scm letter}{revision hash}` versiobn when creating a package which is not correct (And rejected by PyPI). That is why I used `SETUPTOOLS_SCM_PRETEND_VERSION` env variable

Ideally, (2) would be resolved by having zest generating a package from a clean repo with no distance to the tag. This vould generate a `{tag}` version number (see https://pypi.org/project/setuptools-scm/) But this would be changing zest in a deeper way (and there might be another implications) 

> So they'll have to dance very carefully around each other somehow

Exactly, and my workflow seems to do that. If you provide a env variable, I can tell setuptools-scm that if that variable is set, then prvide a simple version number or something like that.

**Comment by reinout** [comment]
Ok, in this way it makes some sense to me :-)
I've started a quick pull request #340 
I first need to get the build to pass.

**Comment by reinout** [comment]
@hgrecco, can you try 6.20.0? It ought to set the `ZESTRELEASER` environment variable.

**Comment by hgrecco** [comment]
The environmental variable works fine, but somehow the package is built with an different version after printing: 
```
Check out the tag (for tweaks or pypi/distutils server upload) (Y/n)?
INFO: Doing a checkout...
```
I will investigate more and let you know.

**Comment by reinout** [comment]
`--verbose` *ought* to help a lot.

**Comment by reinout** [comment]
With the environment variable, I assume the zest.releaser side of things has been fixed, I'm closing the issue for now.
