### ISSUE TITLE
newest release of readme is incompatible with zest.releaser

### ISSUE THREAD

**Issue by do3cc** [zestsoftware/zest.releaser#123]
From readme 0.5.1 to 0.6 the return values of render() have been changed.
Before, it returned two values, now it returns only one value.
It is either the rendered output, or none:
https://github.com/pypa/readme/commit/40caf27bf6f27ad2b9f365202d5baf1c7b381f99#diff-40e9d5b5f74d9d8f5915876cd781c1a9L121

**Comment by reinout** [comment]
There are two things we can do:

- Simply use the new version and add a minimum version of 0.6 to the readme dependency.

- An if/else to check for one or two arguments.

I'm leaning towards the first option. What would you say?

**Comment by reinout** [comment]
Ok, I've done the first one of the two options. See pull request #124 .

**Comment by do3cc** [comment]
Looks good!
