### ISSUE TITLE
Use twine register command

### ISSUE THREAD

**Issue by mauritsvanrees** [zestsoftware/zest.releaser#128]
When a package is not registered yet, we warn:

```
WARNING: This package is NOT registered on PyPI.
WARNING: Please login and manually register this package on PyPI first.
```

twine 1.6.0 was released yesterday, which includes a register command.  We can call that like this:

```
twine register dist/mauritstestpackage2-1.1.tar.gz 
```

Or for a different PyPI server, something like this:

```
twine register -r testpypi dist/mauritstestpackage2-1.1.tar.gz 
```

So call it pointing to some generated file in the dist directory.

**Comment by reinout** [comment]
Twine is a direct dependency, right? Fine, then.

Perhaps also adjust the wording "register and upload" that's still around somewhere. Just "upload" is enough now that we use twine.

**Comment by gforcada** [comment]
:+1: I did not had a distribution registered on pypi and I had to make a second release of it as I didn't really figure out how to push an already released version with zest.releaser... :shame-on-me:

But being able to register + upload would be really convenient.
