### ISSUE TITLE
postrelease - increment number in 'devN'

### ISSUE THREAD

**Issue by matysek** [zestsoftware/zest.releaser#130]
Could it be possible when doing `postrelease` just increment the 'N' in the version when current version is a development version? For example:

```
current:  1.3.dev0
new:      1.3.dev1
```

Usecase: Sometimes I need to do a prerelease of the development version for my project (command `release` - uploading to pypi) and then just continue with development (command `postrelease`) - continue with new development version and not starting with `dev0` but `devN+1`.

Is this feasible extension for zest.releaser?

**Comment by matysek** [comment]
I might try to implement this but I'd like to know if there is interest in this behavior.

**Comment by reinout** [comment]
Such a development version doesn't need to be released, I think. If you want to distinguish between two versions on such a level I'd just manually increment the `1.3.dev0` to `1.3.dev1`.

If you want to do a real proper release, I'd expect at least an alpha or beta release. And even that is something we don't really support automatically as nobody seems to be doing that (except for really really really bit projects like django itself).

So... this is something you should do manually.

Dev markers, I think, are *not* meant to be proper releases.

@mauritsvanrees, do you agree?

**Comment by mauritsvanrees** [comment]
Agreed. PyPI might currently even refuse to accept such releases. I don't know that for sure, but I can imagine.

**Comment by matysek** [comment]
> Agreed. PyPI might currently even refuse to accept such releases. I don't know that for sure, but I can imagine.

@mauritsvanrees PyPI accepts releases with version `1.3.dev0` and you might install them with command `pip install --pre pkg_name`.
