### ISSUE TITLE
Strange change in CHANGES.rst

### ISSUE THREAD

**Issue by jensens** [zestsoftware/zest.releaser#133]
When I release ``collective.recipe.supervisor`` I get a strange change in special characters::

    Enter version [0.20]: 
    INFO: Set setup.py's version to u'0.20'
    INFO: Changed version from 0.20.dev0 to 0.20
    INFO: History file docs/CHANGES.rst updated.
    INFO: The 'git diff':

    diff --git a/docs/CHANGES.rst b/docs/CHANGES.rst
    index 67237b4..0115e91 100644
    --- a/docs/CHANGES.rst
    +++ b/docs/CHANGES.rst
    @@ -1,7 +1,7 @@
     Change history
     **************
     
    -0.20 (unreleased)
    +0.20 (2015-10-06)
     =================
     
     - Fix tests to be able to run.
    @@ -55,13 +55,13 @@ Change history
     =================
     
     - Fix supervisorctl to use unix_http_server if used
    -  [Domen Kožar, NiteoWeb. Work sponsored by Hexagon IT]
    +  [Domen KoĹžar, NiteoWeb. Work sponsored by Hexagon IT]
     
     0.15 (2011-03-05)
     =================
     
     - Added support for unix_http_server additionally to inet_http_server
    -  [Domen Kožar, NiteoWeb. Work sponsored by Hexagon IT]
    +  [Domen KoĹžar, NiteoWeb. Work sponsored by Hexagon IT]

**Comment by reinout** [comment]
Non-ascii characters in the changelog/readme have always been a little bit of a problem. We fixed a lot and the recent python 3 compatibility fixed even more but also broke a few cases again. I *thought* we had it all fixed, though.

Two questions:

- Which zest.releaser version are you using? The last fix was done in 5.2 (late july): "Write file with the same encoding that we used for reading them. Issue #109."

- Python 2 or python 3?

**Comment by jensens** [comment]
I used ``zest.releaser-5.6-py2.7.egg``.

**Comment by reinout** [comment]
I made a clone of collective.recipe.supervisor (which I use in all my buildouts, btw!) and ran prerelease. I'm seeing the same problem locally. I'll see if I can figure out the problem.

**Comment by reinout** [comment]
Looks like a bug in zest.releaser :-) I've added some `logger.debug()` statements and this is what it now tells me:

    DEBUG: Detected encoding of docs/CHANGES.rst with chardet: ISO-8859-2
    ....
    DEBUG: Writing to docs/CHANGES.rst with the default output encoding UTF-8

That last one *should*, if I read the code right, say something like "writing it back with the originally detected encoding".

So: I'll look into fixing it in zest.releaser.

I think it is also handy to change your changelog from ISO-8859-2 to utf-8.

**Comment by reinout** [comment]
Yeah, it works now!

    DEBUG: Writing to docs/CHANGES.rst with its original encoding ISO-8859-2
    INFO: History file docs/CHANGES.rst updated.
    DEBUG: Running command: u'git diff'
    INFO: The 'git diff':

    diff --git a/docs/CHANGES.rst b/docs/CHANGES.rst
    index 290ba09..b9f678e 100644
    --- a/docs/CHANGES.rst
    +++ b/docs/CHANGES.rst
    @@ -1,7 +1,7 @@
     Change history
     **************

    -0.21 (unreleased)
    +0.21 (2015-10-07)
     =================

     - Nothing changed yet.
    diff --git a/setup.py b/setup.py
    index d0df599..478b4cb 100644
    --- a/setup.py
    +++ b/setup.py
    @@ -11,7 +11,7 @@ import os
     def read(*rnames):
         return open(os.path.join(os.path.dirname(__file__), *rnames)).read()

    -version = '0.21.dev0'
    +version = '0.21'

     long_description = (
         read('README.rst') + '\n\n' +


    OK to commit this (Y/n)?

I'll make a pull request and get @mauritsvanrees to take a look and then I'll make a new release.

**Comment by jensens** [comment]
Well, I did not make it ISO-8859-2 :) I at least filed a ticket.
