### ISSUE TITLE
Registering is not run on new packages with zest.releaser 5.6

### ISSUE THREAD

**Issue by Natim** [zestsoftware/zest.releaser#134]
```
WARNING: This package is NOT registered on PyPI.
WARNING: Please login and manually register this package on PyPI first.
Register and upload to pypi (y/N)? yes
INFO: Running: twine upload dist/* -r pypi
HTTPError: 403 Client Error: You are not allowed to edit 'new-package' package information for url: https://pypi.python.org/pypi
```

I though after #119 the register command had been added to twine so that this should work.

**Comment by reinout** [comment]
Well, there's also #128 :-) Twine was added in #119, but twine itself apparently only recently gained the functionality to register. We just haven't added it yet. I think @mauritsvanrees was planning to add that (though a pull request is always welcome).

**Comment by reinout** [comment]
Old issue, I think it can be closed. Registering isn't even possible on pypi anymore and twine handles everything just fine.
