### ISSUE TITLE
Output missing when using --no-input

### ISSUE THREAD

**Issue by mauritsvanrees** [zestsoftware/zest.releaser#136]
Take a package that has no changes in its change log file.  Running standard fullrelease, you get:

```
$ fullrelease
INFO: Starting prerelease.
...
WARNING: Changelog contains u'- Nothing changed yet.'. Are you sure you want to release? (y/N)? 
```

Running with no input, this warning is not shown and the command quits and you have not really an idea what is going on:

```
$ fullrelease --no-input
INFO: Starting prerelease.
...
INFO: You can use the 'lasttaglog' command to see the commits since the last tag.
```

**Comment by reinout** [comment]
So... if you're running with --no-input, there are some things that you normally press "yes" on and some things that should result in `sys.exit('Bugger off')`?

**Comment by mauritsvanrees** [comment]
No. Without no-input I see a warning and with no-input the warning is not visible and it just quits. This leaves me wondering why it stopped.

**Comment by reinout** [comment]
Ah, it gets the "bugger off" part right, but it should be a bit more verbose about it?

**Comment by mauritsvanrees** [comment]
Yes. It seems to be swallowing the warning.

**Comment by reinout** [comment]
Seems to be fixed, right?

**Comment by reinout** [comment]
Seems fixed.
