### ISSUE TITLE
utils.extract_headings_from_history can get confused

### ISSUE THREAD

**Issue by mauritsvanrees** [zestsoftware/zest.releaser#141]
This is while releasing https://github.com/plone/plone.intelligenttext
In the changelog it has this line, which is recognised as header because it contains brackets:

```
- Minor cleanup (pep8, readability, ReST)
```

The result is that we get these headings:

```
[{u'date': u'unreleased', u'line': 4, u'version': u'2.1.0'},
 {u'date': u'pep8, readability, ReST',
  u'line': 14,
  u'version': u'- Minor cleanup'},
 {u'date': u'2015-05-11', u'line': 18, u'version': u'2.0.3'},
 {u'date': u'2013-01-01', u'line': 25, u'version': u'2.0.2'},
 {u'date': u'2010-07-18', u'line': 38, u'version': u'2.0.1'},
 {u'date': u'2010-06-13', u'line': 45, u'version': u'2.0'},
 {u'date': u'2009-04-04', u'line': 52, u'version': u'2.0a1'},
 {u'date': u'2009-04-09', u'line': 59, u'version': u'1.0.3'},
 {u'date': u'2008-07-17', u'line': 72, u'version': u'1.0.2'},
 {u'date': u'2007-12-04', u'line': 84, u'version': u'1.0.1'},
 {u'date': u'mostly taken from Products.intelligenttext',
  u'line': 108,
  u'version': u'- Add unit tests'},
 {u'date': u'2007-08-15', u'line': 112, u'version': u'1.0'},
 {u'date': u'2007-05-07', u'line': 119, u'version': u'1.0b2'},
 {u'date': u'2007-04-07', u'line': 126, u'version': u'1.0-beta1'}]
```

So instead of this as the most recent history:

```
2.1.0 (2015-10-27)
------------------

New:

- Make compatible with Python 3.
  [davisagli]

Fixes:

- Minor cleanup (pep8, readability, ReST)
  [jensens]
```

We get this:

```
2.1.0 (2015-10-27)
------------------

New:

- Make compatible with Python 3.
  [davisagli]

Fixes:
```

No really big deal, but would be nice to fix this, although then we might err in a different direction, not recognising some headings...

**Comment by reinout** [comment]
Wasn't there some detection of the header-style (`=====`, `-----`, `#####`) afterwards? If that fails or is empty there's apparently no header in this location.

**Comment by mauritsvanrees** [comment]
No. I think we are not requiring such underlines.

**Comment by reinout** [comment]
This issue is still valid and still low-prio.
Perhaps we should close it. Fixing it seems a bit dangerous?

**Comment by mauritsvanrees** [comment]
Seems a corner case that does not happen very often. Well, corner cases are like that. ;-)
I did not remember that I opened this issue. :-) And I don't remember coming across this problem since.
Fine to close it.
