### ISSUE TITLE
Warn about lack of PyPI privileges in advance

### ISSUE THREAD

**Issue by mgedmin** [zestsoftware/zest.releaser#145]
ZopeFoundation has many packages.  I have PyPI rights to many of them, but not all.  There are too many packages to remember which ones I can release and which ones I can't.  Sometimes I attempt to release a package I have no upload rights to, and the upload step fails.  This leaves me with a local commit and tag that I must then undo manually.

It'd be nice if zest.releaser checked if my PyPI username (from ~/.pypirc) was listed in PyPI among the maintainers/owners of that package, before actually making any changes to the source tree.

**Comment by reinout** [comment]
Is there an api we can use to query pypi? I see the use for such a feature, but web-scraping pypi isn't the handiest thing to do.

Also: are there scenarios where adding this functionality could bite us? Non-pypi internal company repositories, for instance?

**Comment by mgedmin** [comment]
The [XML-RPC API](https://wiki.python.org/moin/PyPIXmlRpc) lets you get a list of maintainers:
```
>>> import xmlrpclib  # import xmlrpc.client as xmlrpclib on Python 3
>>> client = xmlrpclib.ServerProxy('https://pypi.python.org/pypi')
>>> client.package_roles('ZODB')
[['Owner', 'tseaver'], ['Maintainer', 'tseaver'], ['Owner', 'J1m']]
```
AFAIU both "Owner" and "Maintainer" roles can make releases, and there are no other roles.

I don't see anything similar in the [JSON API](https://wiki.python.org/moin/PyPIJSON).

Long-term, the current PyPI code will be replaced by [Warehouse](https://github.com/pypa/warehouse).  Warehouse also [supports](https://github.com/pypa/warehouse/blob/6828ae38492c4a43eb61bfa74836f1d05b316424/warehouse/legacy/api/xmlrpc.py#L116-L125) the [XML-RPC "legacy" API](https://github.com/pypa/warehouse/blob/6828ae38492c4a43eb61bfa74836f1d05b316424/docs/api-reference/xml-rpc.rst).  Eventually I imagine there will be a new "non-legacy" API, based on JSON, but it's likely to take years.

**Comment by mgedmin** [comment]
Internal repositories: `~/.pypirc` specifies an index server to use, as well as credentials, so we could check if the right user has the right permissions in the right PyPI server, I suppose.

I suggest that failing this new check ought to produce a warning:

    Your user ("mgedmin") is not listed among owners and maintainers of PROJECT.  Continue anyway? [y/N]

This will give me time to ask for pypi rights on IRC, or override an incorrect check.

If people who use internal pypi servers complain, you could add an option to disable this check.

**Comment by reinout** [comment]
Well, if we first check *if* the project is released on pypi... you only have to check for ownership in those cases.

Hm, this does mean we're mixing the release stage and the prerelease stage. We already have quite a number of y/n questions and I wouldn't want any extra (possibly unneeded) warnings.

@mauritsvanrees: how about an optional check? Something you enable in .pypirc? What do you think?

**Comment by mgedmin** [comment]
If this check succeeds (name is not registered on PyPI *or* you're a maintainer/owner), there shouldn't be any questions.  The question should show up only if the check fails.

Do you think false positives are likely?

**Comment by reinout** [comment]
Some be-a-bit-careful brainstorming of corner cases:

- Internal projects that are copies/clones of existing projects, for instance. Bugfixes/tweaks.

- It is an extra external URL we're accessing. So you need internet access. Does that work for everyone? Not everyone releases to pypi and some people might use zest.releaser without access to external networks.

- You can also use zest.releaser for projects without setup.py (we have several non-python projects with a version.txt and a changes.rst). Such projects can also easily overlap with a pipy name. Of course we can check whether there's a setup.py first, but slowly the amount of extra lines of code starts to mount :-)

**Comment by mgedmin** [comment]
Can you do this check if and only if you're going to call twine to upload things?

**Comment by reinout** [comment]
Determining what to in the release step (like using twine) happens in the release step.

That's the practical downside to your feature request: things we already check or might want to check in the release step suddenly *also* have to be done in the prerelease step :-) Or actually *before* the release step.

That is... you wanted to be told *before* making any code changes whether you have write access to the pypi package, right?

I'm slowly leaning towards a separate command "bin/check_pypi_status" or so that prints whether the project in question is on pypi and whether you've got rights. Then it doesn't interfere with the regular program flow.

**Comment by mauritsvanrees** [comment]
I use the plone.releaser package for releasing core Plone packages. It uses the zest.releaser extensions mechanism, among others for checking PyPI rights:
https://github.com/plone/plone.releaser/blob/1.3/setup.py#L53
If course in the Plone case we always want to release to PyPI, so internal packages are no concern.
It works quite well: if it sees I have no PyPI rights, I can open an editor and fix my pypirc (I have my own account and a plone account) and then answer 'yes' to the question if I want to continue.

**Comment by reinout** [comment]
If the code is already there in plone.releaser... We could copy that :-)

To prevent corner cases, we could make it an opt-in function? `check_pypi_rights = true`?

**Comment by mauritsvanrees** [comment]
I have actually recently basically disabled this check in `plone.releaser`.  
It no longer worked well now that we have a `plone` PyPI organisation.  See https://github.com/plone/plone.releaser/issues/50 describing the problem, and https://github.com/plone/plone.releaser/pull/51 with my changes.

The check we do, uses an XML RPC client to access pypi.org and this is [deprecated](https://warehouse.pypa.io/api-reference/xml-rpc.html).

So I vote for not doing this.
