### ISSUE TITLE
Release arbitrary packages

### ISSUE THREAD

**Issue by gforcada** [zestsoftware/zest.releaser#146]
Would it be possible/feasible to make zest.releaser be able to release any given package?

By that I mean a scenario like:
- buildout.coredev has been cloned and buildout ran
- bin/fullrelease is available
- a package in src/plone.app.dexterity needs a release
- from within buildout.coredev you run `./bin/fullrelease src/plone.app.dexterity`

AFAICS right now you can only release the very same package you are on, but not others.

One quick and dirty hack would be to get the path as a parameter, do an `os.chdir(PATH_TO_PACKAGE)` and then continue the release from there.

Would this be something that could be integrated into zest.releaser?

**Comment by reinout** [comment]
You can already do what you want:

    $ cd src/plone.app.dexterity
    $ ../../bin/fullrelease

I'm a bit afraid of doing a "cd" as there are at least six places where we need to "cd" or "cd back". Easy for something to go wrong. And I don't know if all of the zest.releaser extensions like it.

@mauritsvanrees, any ideas on this? You're one of the I-want-to-release-50-plone-packages-within-5-minutes persons :-)

**Comment by mauritsvanrees** [comment]
I am also thinking: what is wrong with doing a 'cd' yourself on the command line? Unless you want to be able to do `bin/fullrelease src/*` which I don't think is something we should support.

**Comment by gforcada** [comment]
@mauritsvanrees my use case here at der Freitag is to be able to do something like:

```
bin/fullrelease src/X src/Y src/Z
```
That's the reason I started https://github.com/derFreitag/freitag.releaser, to mix/enhance plone.releaser and zest.releaser.

My goal is that with a single command (``./bin/freitag_manage do-the-magic``) I can check all packages inside ``src/`` and if they have changes and everything is fine (code analysis, manifest, translations, etc etc) do a release and update parent project versions.cfg and so on.

I can already script that with what @reinout just said, so it's fine for me to not add the +6 cds all over the place.

**Comment by reinout** [comment]
Closing this (old) issue :-)
