### ISSUE TITLE
postrelease hangs when using ssh with ControlMaster auto

### ISSUE THREAD

**Issue by mgedmin** [zestsoftware/zest.releaser#150]
**Background**

I use SSH connection multiplexing to speed up GitHub access, by having this in my ~/.ssh/config:

```
Host *
ProtocolKeepAlives 300
ServerAliveInterval 300
ControlPath ~/.ssh/control-%r@%h-%p
ControlPersist yes

Host github.com
ControlMaster auto
```

This has a certain downside: if I git pull/push something at work, then suspend my laptop, go home, and resume it, there's still a background SSH process that thinks it has a valid TCP connection to GitHub.  The next git pull/push I do at home will hang for 5 minutes, until the control master realizes its connection is dead.

I don't have the patience to wait 5 minutes, so I have a small shell script that tells the existing ssh control master process to quit:

``` sh
ssh -O exit git@github.com
```

So what usually happens: I do `git push`, see that it's stuck, realize what happened, run my `kill-ssh-control-master-for-github` script, which makes the `ssh` process spawned by git emit some error to stderr (this is probably important!) and then open a new connection to github, which then makes `git push` succeed faster than if I'd waited for the 5 minutes.

**Problem description**

I ran `postrelease` to update the version number and changelog and let it do the push.  The push took longer than I expected, at which point I realized I had a stale ssh control master and ran my `kill-ssh-control-master-for-github` script.  At this point postrelease emitted

```
OK to push commits to the server? (Y/n)? 
INFO: To git@github.com:mgedmin/check-manifest
9090fa7..9be5a51  master -> master
```

and then froze.

Note how there's no stderr message that I know gets produced by ssh when its control master gets unexpected killed.

**Analysis**

I can see with pstree that the git subprocess is finished -- there's only a zombie sh:

```
$ pstree -ap 19850
postrelease,19850 /home/mg/.venv/bin/postrelease
  └─(sh,19886)
```

`strace -p 19850` tells me `zest.releaser` is blocked reading from fd 7.

```
$ lsof -p 19850
...
postrelea 19850   mg    7r  FIFO   0,10      0t0 2591989 pipe
...

$ lsof | grep 2591989
postrelea 19850                    mg    7r     FIFO               0,10      0t0    2591989 pipe
ssh       19922                    mg    2w     FIFO               0,10      0t0    2591989 pipe
```

**Conclusion**

It is immaterial that I killed the old ssh master process when postrelease had spawned a new one.  What's important is that the ssh spawned by git spawned by postrelease decided to become the new master process, so it sent itself to the background, but did not close its stderr.  And now zest.releaser is blocked trying to read its stderr.

I don't know if zest.releaser can do anything to mitigate this.  I don't know if it should.

**Workaround**

I can run my `kill-ssh-control-master-for-github` again, which unlocks the postrelease script and makes it emit

```
INFO: To git@github.com:mgedmin/check-manifest
* [new tag]         0.29 -> 0.29
```

and then exit.

**Comment by reinout** [comment]
The only thing that happens at the end, where it hangs for you, is a `git push`, a `git push --tags` and printing the location of the /tmp directory with the checked-out tag (if any) in it.

At least the `git push --tags` got through OK, you might want to check if the first `git push` succeeded.

Further... I don't immediately know what zest.releaser could do about this. If I remember correctly, the external-command-running stuff was inspired by the code in buildout. Some Popen() magic, probably.

**Correction:** I just looked. That method has grown "a bit" compared to the one I had in my memory :-) Mostly having to do with color-coding the output, detecting errors *and partially excluding the stderr*. Perhaps you can take a look there if you spot something obviously wrong? The amount of comments in that piece of code (link below) tells me it was hard to get it right and also that it was painstakingly made to be correct :-) Perhaps it rings one of @mauritsvanrees's bells?

https://github.com/zestsoftware/zest.releaser/blob/master/zest/releaser/utils.py#L552

**Comment by mauritsvanrees** [comment]
I had tried that `ControlPersist` ssh configuration a few years ago but could not get it to work reliably, or maybe at all. Trying again now with a similar config, although my ssh does not have the `ProtocolKeepAlives` option. Useful background info for these options:
https://patrickmn.com/aside/how-to-keep-alive-ssh-sessions/

And with that, I can confirm this problem. When I have not accessed github.com with ssh in the past five minutes, the postrelease will hang. The push has succeeded, but the process is still alive, so postrelease can't continue. Doing a git fetch or pull first makes it work just fine.

As a test I have set `ControlPersist 10` in the config, so the connection is persisted for ten seconds. Then the push command in postrelease seems to hang and then gives feedback:

```
# After ten seconds:
INFO: To git@github.com:mauritsvanrees/mauritstestpackage.git
759feb5..5531e77  master -> master
# After another ten seconds, because it is a new command:
INFO: To git@github.com:mauritsvanrees/mauritstestpackage.git
* [new tag]         1.14 -> 1.14
```

Maybe we can read the output line by line and have a timeout: when reading a line takes more than ten seconds, print the output we gathered so far and maybe ask the user if he wants to wait a bit more, or kill the child process or retry or quick the postrelease.

Or catch a KeyboardInterrupt.

**Comment by mauritsvanrees** [comment]
Some interesting timeout options in the answers here: http://stackoverflow.com/questions/1191374/using-module-subprocess-with-timeout

**Comment by mgedmin** [comment]
Idea: stop reading the stdout + stderr when the direct child process quits; let any background daemons deal with SIGPIPE.

Implementing it would probably mean you can't use Popen.communicate() any more, but have to do a manual select() loop while also polling the exit status.

Is it worth it?  I don't know.

**Comment by mauritsvanrees** [comment]
I just noticed that checkoutmanager has the same problem: when I ran `checkoutmanager up` this morning, it hang at the end.

Might be nice to play with `select`. I did not know this core library. Well, I still don't know it, but now I at least know it exists and might be able to help in a situation like this. :-)

We are not using `Popen.communicate()` btw, but directly writing the input and reading the output/error files. Using `communicate()` does seem a bit nicer.

**Comment by mgedmin** [comment]
FWIW I meant select() the Unix system call rather than a specific Python implementation.  I'd no idea [select](https://docs.python.org/3/library/select.html) existed in the standard library.

**Comment by vphantom** [comment]
FYI OpenSSH <7.3 had a bug <https://bugzilla.mindrot.org/show_bug.cgi?id=1988> which caused `stderr` to remain open until the background process terminated. This issue may be obsolete.

**Comment by reinout** [comment]
Sounds like that could have been the problem, yes. Closing the issue. It can always be re-opened if needed.
