### ISSUE TITLE
fullrelease fails to commit to SVN when client is 1.8 or above (--non-interactive)

### ISSUE THREAD

**Issue by keul** [zestsoftware/zest.releaser#151]
Found the same issue on mr.developer. Please see https://github.com/fschulze/mr.developer/issues/177

Briefly: usage of SVN is now a nightmare because SVN 1.8 changed a core behavior: you must explicitly put a `--force-interactive`.

**Comment by gotcha** [comment]
@keul Switch to git ;-)

**Comment by keul** [comment]
:smile:

**Comment by mauritsvanrees** [comment]
I have not seen problems with svn. Locally I have svn 1.8.13 and the tests are running fine and the last fullrelease I did on an actual project was fine too. But maybe the server has an earlier version and maybe  that helps.

What do you see going wrong? Is there an error message?

**Comment by keul** [comment]
@mauritsvanrees the issue hits you only if you don't have the SVN password stored locally so I can't read the full error message.

Probably it was one one the many you can find googling it, like:

    Authentication failed and interactive prompting is disabled; see the --force-interactive option

Releaser will not ask you for SVN password but returns the error message.

**Comment by reinout** [comment]
As it seems like a corner case (no stored svn password locally) and as I guess svn usage is very low nowadays, I'm going to close the issue for now.
