### ISSUE TITLE
Add a config to ask for tag signing or/and commit signing

### ISSUE THREAD

**Issue by Natim** [zestsoftware/zest.releaser#152]
`git config --get user.signingkey`

**Comment by Natim** [comment]
Instead of ``git tag version -m "Tagging version"`` we could use: ``git tag -s version -m "Tagging version"`` in that case.

**Comment by reinout** [comment]
Is there an option for git to do this automatically? I mean, if a signing key is defined, why doesn't git use it?

**Comment by Natim** [comment]
Apparently the ``-s`` options works even if no configuration has been set in the ``.gitconfig`` (using default gpg key)
I suppose that it should be a zest.releaser option to let the user decide if the zest.releaser tag must sign tags or not.

**Comment by Natim** [comment]
Another solution would be for me to define the tag alias as: ``tag = tag -s``

**Comment by reinout** [comment]
Where would the configuration be most handy? If you do it in zest.releaser, it applies to everyone that releases the project. If you do it via a git alias, it only applies to you. I don't know which occurs most often.

I'm not too fond of adding yet another question to zest.releaser. If the option gets added, it won't be a question as the project owner apparently *requires* everyone that does a release to sign it.

**Comment by Natim** [comment]
I was thinking of adding this option to the ``setup.cfg`` as we already do with the create-wheel option:
```
$ cat setup.cfg 
[zest.releaser]
create-wheel = yes
```

Could be:

```
$ cat setup.cfg 
[zest.releaser]
tag-signing = yes
commit-signing = yes
```

**Comment by reinout** [comment]
That would probably be the best way to do it. I probably would leave out the commit signing and only do tag signing. Commit signing isn't (from what I read) universally accepted as a good idea. And it doesn't make much sense to only sign the pre/post release steps. Signing tags *does* seem more useful.

Note https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work#Everyone-Must-Sign :

*Signing tags and commits is great, but if you decide to use this in your normal workflow, you’ll have to make sure that everyone on your team understands how to do so. If you don’t, you’ll end up spending a lot of time helping people figure out how to rewrite their commits with signed versions. Make sure you understand GPG and the benefits of signing things before adopting this as part of your standard workflow.*

So: I can see the use of signing tags, though I probably won't use it myself.

**Comment by Natim** [comment]
It is just an information to make sure the person who have tagged is the one pretending to be.
If you do continuous integration using Git you would probably want to make sure the tag to deploy is the one that need to ship.

**Comment by reinout** [comment]
The word "just" makes it sound like something easy and small :-) But properly setting up PGP is quite some work. Getting all contributors/colleagues to set it up correctly is even more work.

That is why I'm surprised git seems to treat it as something optional you can enable as an individual developer. I mean, if your project really needs it you should be able to configure it like that in git directly, not depend on something like zest.releaser to do it for you.

Apparently git doesn't, so zest.releaser might be the right place to do it :-)

**Comment by Natim** [comment]
> But properly setting up PGP is quite some work.
Why? It is just a matter of creating the key and sending it on a SKS server?

Then adding each contributor public key that can tag to you locally so that you can validate the tag first.

If people already use PGP to sign their email everything is automatically taken into account with git.

**Comment by reinout** [comment]
"Just" a matter of creating the key: and making a proper off-site backup of your private key. And making sure you refresh it before expiry date. And learning the commands. And figuring out what PGP even *is*.

Anyway, no need to discuss PGP usage :-)

**Comment by htgoebel** [comment]
:+1: for tag-signing

**Comment by k4nar** [comment]
That would be a very great feature. I often answer No when asked if I want to run the `git tag` command, and tag manually with `-s` instead.

The `setup.cfg` seems to be the best place to put it indeed.

**Comment by mauritsvanrees** [comment]
The `-s` should be added in [`cmd_create_tag`](https://github.com/zestsoftware/zest.releaser/blob/6.7.1/zest/releaser/git.py#L83). It should be conditional on a `setup.cfg` or `~/.pypirc` option.

But if you add it there, does it actually work? It seems so: in a local test I got it to sign the tag this way. But I had already signed a tag manually before that, so something (maybe `gpg-agent`) had remembered my passphrase. So I wonder if it still works when you haven't yet done that: does asking for a passphrase work, or does `zest.releaser` swallow the input, or maybe display it in clear text? I do have a gpg key, but I hardly use it, so I don't really know how to test this properly.

Anyway, this sounds like a fine one for a pull request.

**Comment by mauritsvanrees** [comment]
If we add this, it would be nice to do this for subversion, mercurial and bazaar too. We try to keep parity in features for those. But they may not have this option. So if this is only supported for git, we can mention this in a changelog entry and the documentation.

**Comment by Natim** [comment]
What I did is to setup auto gpgsign in my gitconfig:

```
[commit]
gpgsign = true

[tag]
gpgsign = true
```

An everything works like a charm.

**Comment by k4nar** [comment]
That's actually a better option, thanks Rémy!

**Comment by mauritsvanrees** [comment]
That seems better yes. I have added a few lines of documentation about this. Thanks.

**Comment by htgoebel** [comment]
I ask to reopening and implementing this. The discussion above recommenss to set "commit.gpgsign" and "tag.gpgsign" in the git config.

This has several drawbacks:
1. According to [the official docs](https://git-scm.com/docs/git-config) there is no option "tag.gpgsign", only one for the commits.
2. This config can not be stored with the *project* (in an version controlled file), but is configured in the *one, specific* repo-clone. Even if the same developer clones the repo, this config-option is not cloned.

Thus I suggest and ask for having `tag-signing` in `setup.cfg`, as described above.

IMHO there is no need for an option `commit-signing`, since it make no sense to only sign the release commit, but not the others. Thus is a project wants to sign every commit, the developers have to set "commit.gpgsign" anyway.

In our project we only sign *release tags*, not every commit.

***Implementation***

```
$ cat setup.cfg 
[zest.releaser]
tag-signing = yes
```

If this option is "True", `--sign` should be passed to `git tag`.

**Comment by reinout** [comment]
You're right: tag signing is something different from generic commit signing. It sounds like a good option to add. I'll reopen the issue for now.

Tag signing, could that also work for other version control systems like mercurial?

**Comment by htgoebel** [comment]
The [mercurial wiki says so](https://www.mercurial-scm.org/wiki/Tag), but does not tell how :-(

**Comment by Natim** [comment]
This works right?

```
[commit]
gpgsign = true

[tag]
gpgsign = true
```

**Comment by htgoebel** [comment]
@Natim This example is wrong. git does not have an option to sign only tags (tag.gpgsign). It has only an ption to sign *all* commits (commit.gpgsign)  Read [the official docs](https://git-scm.com/docs/git-config).

**Comment by Natim** [comment]
I don't know but I have been using it for the past 2 years :/ Is a tag considered as a commit?

**Comment by htgoebel** [comment]
Yes, a tag is a commit, as each tag is committed. But we want to only sign *tags*, not each commit, so setting "commit.gpgsign" is not what we want.

**Comment by tarioch** [comment]
Actually git now has an option for tag signing:

```
[tag]
        forceSignAnnotated = true
```
Works fine for me

**Comment by htgoebel** [comment]
This has the *big* drawback that it depends on the individual developers repo-configuration whether tags will be signed. I'd prefer if this is coded into the tooling.

**Comment by tarioch** [comment]
I agree, that this would be nicer

**Comment by reinout** [comment]
In the end, you *have* do do something as an individual developer anyway: setting up your gpg toolchain. So by adding the option, you make releasing impossible for the ones that haven't set it up. (Which might be exactly what you want).

Which also means that there'll have to be error handling explaining what is going on if you haven't configured it yet. This starts to sound a bit like a lot of work. I'd have to see a pull request to know if I like it or not. Perhaps it is fine.

There won't be many people making releases, I think? Isn't it enough to make sure the two or three doing it have set their repo up in the right way?

Anyway, I'm starting to lose track a bit about what I like/want :-) => @mauritsvanrees ?

**Comment by mauritsvanrees** [comment]
@htgoebel thought of this implementation:

> $ cat setup.cfg 
> [zest.releaser]
> tag-signing = yes
> If this option is "True", --sign should be passed to git tag.

In that way, the setting is stored on the project, which makes sense. I can imagine that we want this in the future in the Plone project.
If the option is 'no' then we simply do not pass `--sign`, so the settings of the developer are respected.

A pull request would be helpful. Biggest issue may indeed be: check what happens when the option is true and the user has not setup gnupg correctly, and give a helpful message then.
