### ISSUE TITLE
Show last release and changelog prior to choose the next version

### ISSUE THREAD

**Issue by gforcada** [zestsoftware/zest.releaser#155]
Background: I created [freitag.releaser](http://pypi.python.org/pypi/freitag.releaser) to be able to release packages in a bulk, it's basically a wrapper around zest.releaser.

Thus whenever I release some packages I never remember what was the last release version nor what where exactly the changes in each of the packages.

These two, changelog for the next release and the last release number, are the pieces of information I need to decide which version number I want to release.

So, would it be possible to show the changelog and the last version released before entering the next release number?

**Comment by mauritsvanrees** [comment]
plone.releaser uses an entry point to show the changelog:
https://github.com/plone/plone.releaser/blob/957e402ef8a4f7a30c3190b305b8828d8726edc1/plone/releaser/release.py#L60

Maybe we could incorporate this in zest.releaser.

Showing the last version number: usually the recommended version is fine for me.  Do you often choose a different version?

Then again, it might be easy to do: if we show the changelog, we could show two lines more to include the next header and its underline in the file. That does need some care, as the code that we use for grabbing the history currently expects that the new version number has already been specified by the user.

**Comment by mauritsvanrees** [comment]
I am trying it out now.  This shows when I do a prerelease of zest.releaser with that code (with minor edits for clarity):

```
$ prerelease 
Wrote entry point documentation to .../zest.releaser/doc/source/entrypoints.rst
Run pyroma on the package before tagging? (Y/n)? n
Do you want to run check-manifest? (Y/n)? n
Changelog entries for version 6.6:

6.6 (2016-01-08)
----------------

- Nothing changed yet.


6.5 (2016-01-05)
----------------
Enter version [6.6]: 
```

**Comment by reinout** [comment]
Note that there's also "lasttaglog" that shows the (git) log messages since the last release. That might be too elaborate for your needs, though.

**Comment by reinout** [comment]
With #156, I assume the issue is fixed?
(I'm going through old issues).
