### ISSUE TITLE
Add a config for tag-prefix

### ISSUE THREAD

**Issue by htgoebel** [zestsoftware/zest.releaser#157]
We are tagging our changes with the prefix `v`. zest.releaser should be be allow specifying this.

**Comment by mauritsvanrees** [comment]
So:
- setup.py still gets for example 1.0, without the `v`.
- The changelog file says 1.0, without the `v`.
- Only the tag gets named `v1.0`.

Is that correct?

I guess we could read a value from the `setup.cfg` or the `~/.pypirc`:  `tag-prefix = v`.
Or possibly `tag-format = v%(new_version)s`.
Or add something like that in the data that we pass around between the release phases, so you could change it in an extension.
