### ISSUE TITLE
Add addchangelogentry command

### ISSUE THREAD

**Issue by mauritsvanrees** [zestsoftware/zest.releaser#159]
For batch editing a bunch of packages, it would be handy to have an `addchangelogentry` command. Calling it with `"blah blah"` would add a line in the changelog file. It would have the standard release command stuff, like showing the diff before asking to commit.

Maybe end it by offering to push as well, but it is probably better to skip this.  Expected usage is:

- Make some change (for example remove/add PyPI classifiers from/to setup.py), possibly done with a script.
- addchangelogentry "my entry text"
- fullrelease (which will offer the push already)

Background for this idea is batch editing a bunch of zope packages to remove the Python 3.2 classifier from setup.py:
https://mail.zope.org/pipermail/zope-dev/2016-January/047076.html

**Comment by reinout** [comment]
Sounds OK
