### ISSUE TITLE
Warn if release number is less than latest.

### ISSUE THREAD

**Issue by jensens** [zestsoftware/zest.releaser#166]
see also plone/plone.app.blocks#24

There is a chance that a release of a version 1.1 hide the prior release of version 2.0. It would be helpful to get a warning like: "You are going to upload version 1.1. This may hide latest release 2.0"

I dont know what information one may gather from PyPI here, i.e. if its possible to predict the real implications. Dependent on the settings in PyPI, 2.0 may not be hidden after the release, but with default setting is will be hidden.

**Comment by reinout** [comment]
Making (bugfix) releases of older versions happens a lot.

Does the warning help anything? Will it make you do something else (like not releasing the bugfix)?

**Comment by jensens** [comment]
At least the warning reminds me to login to pypi and check visibility. If zest.releaser handles visibility (using some PyPI API if there is one) this would be also cool. But its not trivial i guess.

**Comment by do3cc** [comment]
I'd love if zest.releaser could look at setup.cfg for maintained branches, and then take care that after release the latest patch version of each maintained branch is marked visible.
Then it would be good to have printed out, which packages are visible.
Then there is a chance to notice, if setup.cfg is outdated.
This is a lot of functionality.

**Comment by mauritsvanrees** [comment]
I think this is best done as an extra package that registers an entry point for `release.after`. Best done similarly to `pyroma` and `check-manifest`: as a package that is usable on its own and as zest.releaser extension.

**Comment by reinout** [comment]
I'm closing this old issue:
- An extension is a better place for the functionality than core zest.releaser.
- Twine does the uploading now.
- Probably pypi changed its UI a couple of times, so the problem might not be relevant anymore.

**Comment by mauritsvanrees** [comment]
> Probably pypi changed its UI a couple of times, so the problem might not be relevant anymore.

I think this is indeed no problem anymore.  On PyPI you now always see the latest final release.

* https://pypi.org/project/zest.releaser/ currently shows version 8.0.0 and shows a checkmark for "latest version".
* Via the Release history you can go to the very latest release which is an alpha version: https://pypi.org/project/zest.releaser/9.0.0a1/.  That shows a warning: "Stable version available: 8.0.0".
* https://pypi.org/project/zest.releaser/7.3.0/ shows an error: "Newer version available: 8.0.0".
