### ISSUE TITLE
Shallow clones?

### ISSUE THREAD

**Issue by gforcada** [zestsoftware/zest.releaser#169]
When releasing a distribution zest.releaser clones the repository locally to perform some actions.

Some repositories have quite a long history and/or big files on it, so a git shallow clone would speed it up.

That can only work if later on no ``git push`` is done from that repository though.

**Comment by reinout** [comment]
The clone is only used to call "python setup.py sdist/wheel", there's no "git push" happening. So.... sounds like a good idea.

Sounds like a simple option you have to add to the `git clone` command? That wouldn't even need a new test. If the existing tests keep running, that's fine enough :-)

One thing to watch out for: is the option available for all git versions?

**Comment by gforcada** [comment]
Starting from git 1.5.0 there is some support of shallow clones: https://github.com/git/git/blob/8d530c4d64ffcc853889f7b385f554d53db375ed/Documentation/RelNotes/1.5.0.txt

Given that it was released on **14 Feb 2007**, I would say it's quite safe already :-)

**Comment by do3cc** [comment]
@mauritsvanrees This ticket can be closed, no?

**Comment by mauritsvanrees** [comment]
Ah, true. Thanks.
