### ISSUE TITLE
Add documentation for adding hooks via setup.cfg

### ISSUE THREAD

**Issue by embray** [zestsoftware/zest.releaser#172]
As brought up in astropy/astropy#4650, some years ago I added an ability to specify releaser hooks in the `[zest.releaser]` section of `setup.cfg`:  zestsoftware/zest.releaser@6235dad

But this feature never made it into the documentation.  IMO this is generally a better way to specify project-specific hooks since it doesn't pollute a global namespace (entry-points), so long as the given functions can be imported at release-time.

**Comment by mauritsvanrees** [comment]
Ah, true. I totally forgot about that. If you have a working example that would be good.

**Comment by reinout** [comment]
Closing an old issue: we've somehow fixed it in the last couple of years :-) https://zestreleaser.readthedocs.io/en/latest/entrypoints.html#entry-point-specification
