### ISSUE TITLE
release no longer supports version.txt in a python package

### ISSUE THREAD

**Issue by fredvd** [zestsoftware/zest.releaser#175]
With old school package versioning we used to put a version.txt somewhere in the package and put

`
version = open(os.path.join("collective", "mypackage", "version.txt")).read().strip()`

zest.releaser would yell at me bout finding multiple locations to fix/update the version, but it would pick the correct one and I could continue. Somewhere in the last months this 'feature' or backward compatibility seems to have been broken. With an old style package containing version.txt I now get:

/tags/2.0.dev0 -m "Tagging 2.0.dev0"
Run this command (Y/n)? ^CTraceback (most recent call last):
  File "/users/fred/buildouts/zest.tools.buildout/bin/release", line 43, in <module>
    sys.exit(zest.releaser.release.main())
  File "/Users/fred/.buildout/eggs/zest.releaser-6.6.4-py2.7.egg/zest/releaser/release.py", line 260, in main
    releaser.run()
  File "/Users/fred/.buildout/eggs/zest.releaser-6.6.4-py2.7.egg/zest/releaser/baserelease.py", line 308, in run
    self.execute()
  File "/Users/fred/.buildout/eggs/zest.releaser-6.6.4-py2.7.egg/zest/releaser/release.py", line 64, in execute
    self._make_tag()
  File "/Users/fred/.buildout/eggs/zest.releaser-6.6.4-py2.7.egg/zest/releaser/release.py", line 92, in _make_tag
    if utils.ask("Run this command"):
  File "/Users/fred/.buildout/eggs/zest.releaser-6.6.4-py2.7.egg/zest/releaser/utils.py", line 345, in ask
    input_value = get_input(q)
  File "/Users/fred/.buildout/eggs/zest.releaser-6.6.4-py2.7.egg/zest/releaser/utils.py", line 278, in get_input
    result = input(question)
KeyboardInterrupt

Without any listing of alternative version locations found. I cannot find this changed behaviour back int he zest.releaser changelog? Is this intentional? No problem to update some packages, but maybe this is an unwanted side effect of other recent changes in zest.releaser.

**Comment by reinout** [comment]
Hi Fred :-)

I still use `version.txt` (or rather `version.rst`) for non-python-package projects myself, so a version file should still work.

Perhaps it doesn't fully work because you're setting a "version" variable in your setup.py (it seems). 

Can you run "prerelease -v"? The output should help to see what zest.releaser is doing regarding versions.

**Comment by mauritsvanrees** [comment]
I had this just now when making a new release for an old branch of Poi. `prerelease` did not want to update the `version.txt`. It could be that this was because it was a wrongly spelled development version: [`1.2.14dev`](https://github.com/collective/Products.Poi/commit/bac56bd8a2819e4837affdb4d281910d585a1a9a).
I changed it manually so prerelease could continue. After this, postrelease had no problem at all.

So it could be that `zest.releaser` gets confused when the version number is bad.  In fact, when I now do another `prerelease` (for 1.2.15), all is well.

The error with `prerelease -v`:

```
DEBUG: Running command: u'/usr/local/opt/python/bin/python2.7 setup.py egg_info'
DEBUG: Stderr of running command '/usr/local/opt/python/bin/python2.7 setup.py egg_info':
/Users/maurits/shared-eggs/setuptools-23.0.0-py2.7.egg/setuptools/dist.py:285: 
UserWarning: Normalizing '1.2.14dev' to '1.2.14.dev0'
  normalized_version,

DEBUG: Running command: u'/usr/local/opt/python/bin/python2.7 setup.py --version'
DEBUG: Stderr of running command '/usr/local/opt/python/bin/python2.7 setup.py --version':
/Users/maurits/shared-eggs/setuptools-23.0.0-py2.7.egg/setuptools/dist.py:285: 
UserWarning: Normalizing '1.2.14dev' to '1.2.14.dev0'
  normalized_version,

DEBUG: Extracted version: 1.2.14.dev0
DEBUG: Version indicates development: 1.2.14.dev0.
DEBUG: Removing debug indicators: u'1.2.14.'
Enter version [1.2.14]: 
DEBUG: Set heading from u'1.2.14 (unreleased)' to u'1.2.14 (2016-12-09)'.
DEBUG: Set line below heading to u'-------------------'
DEBUG: Running command: u'git ls-tree -r HEAD --name-only'
DEBUG: Found Products/Poi/version.txt
DEBUG: Running command: u'/usr/local/opt/python/bin/python2.7 setup.py egg_info'
DEBUG: Stderr of running command '/usr/local/opt/python/bin/python2.7 setup.py egg_info':
/Users/maurits/shared-eggs/setuptools-23.0.0-py2.7.egg/setuptools/dist.py:285: 
UserWarning: Normalizing '1.2.14dev' to '1.2.14.dev0'
  normalized_version,

DEBUG: Running command: u'/usr/local/opt/python/bin/python2.7 setup.py --version'
DEBUG: Stderr of running command '/usr/local/opt/python/bin/python2.7 setup.py --version':
/Users/maurits/shared-eggs/setuptools-23.0.0-py2.7.egg/setuptools/dist.py:285: 
UserWarning: Normalizing '1.2.14dev' to '1.2.14.dev0'
  normalized_version,

DEBUG: Running command: u'git ls-tree -r HEAD --name-only'
DEBUG: Found Products/Poi/version.txt
DEBUG: Detected encoding of setup.py with chardet: ascii
ERROR: We could read a version from setup.py, but could not write it back. 
See http://zestreleaser.readthedocs.io/en/latest/versions.html for hints.
Traceback (most recent call last):
  File "/Users/maurits/tools/bin/prerelease", line 45, in <module>
    sys.exit(zest.releaser.prerelease.main())
  File "/Users/maurits/tools/src/zest.releaser/zest/releaser/prerelease.py", line 128, in main
    prereleaser.run()
  File "/Users/maurits/tools/src/zest.releaser/zest/releaser/baserelease.py", line 308, in run
    self.execute()
  File "/Users/maurits/tools/src/zest.releaser/zest/releaser/prerelease.py", line 92, in execute
    self._write_version()
  File "/Users/maurits/tools/src/zest.releaser/zest/releaser/baserelease.py", line 240, in _write_version
    self.vcs.version = self.data['new_version']
  File "/Users/maurits/tools/src/zest.releaser/zest/releaser/vcs.py", line 261, in _update_version
    raise RuntimeError("Cannot set version")
RuntimeError: Cannot set version
```

**Comment by reinout** [comment]
Closing the issue, as it seems to be solved (by fixing the version number).
