### ISSUE TITLE
postrelease next version proposition should propose a minor instead of a patch release

### ISSUE THREAD

**Issue by Natim** [zestsoftware/zest.releaser#177]
Most of the time the next release of a package is a minor but it is really unlikely to be a patch release (do you really except to release a version with a bug in it?)

I think when releasing ``3.2.0`` the version proposed should be ``3.3.0.dev0`` and not ``3.2.1.dev0``

**Comment by mauritsvanrees** [comment]
Yes, I regularly make patch releases. In fact, I think most releases I do are patch releases. Latest `zest.releaser` version is 6.6.4.

If you almost never do a bugfix release, you can release version `3.2`: then the proposed version will be `3.3.dev0`.

BTW, if after postrelease you decide you want to increase the minor version you can call `bumpversion --feature`.

**Comment by Natim** [comment]
> if after postrelease you decide you want to increase the minor version you can call bumpversion --feature.

Ok thanks.
