### ISSUE TITLE
Is there a way to skip some extras all the time?

### ISSUE THREAD

**Issue by hvelarde** [zestsoftware/zest.releaser#184]
I don't want to answer to this all the time:

```
Run pyroma on the package before tagging? (Y/n)? n
Do you want to run check-manifest? (Y/n)? n
```
is this configurable in some way?

**Comment by mauritsvanrees** [comment]
No, at least not in a `setup.cfg`, `~/.pypirc` or a command line option.

If you don't want these, then don't install `pyroma` and `check-manifest`, which are included with `zest.releaser[recommended]`. Maybe create a virtualenv where you install plain `zest.releaser` without extras, and use that for projects where you only want the basics.
