### ISSUE TITLE
Check fad sdist .tar.gz files

### ISSUE THREAD

**Issue by miohtama** [zestsoftware/zest.releaser#19]
There could be some kind of logic to check if sdist did not produce a egg which look legit.

One common reason is that MANIFEST.in has some errors and it simply does not include the main directory of your package.

Could it be simple to add logic that sdist contains at least one file which is not __init__.py?

**Comment by reinout** [comment]
@mauritsvanrees : would check-manifest be something for the recommended list? See #49

**Comment by mauritsvanrees** [comment]
@reinout: definitely, it was already on that list for me. :-)

And that seems enough reason to close this issue.

Alternatively, either zest.releaser or a plugin could actually try installing it in a virtualenv:

```
virtualenv dummy
cd dummy
bin/pip install --no-deps ../dist/my-distribution-file.tgz
```

Or with similar code after the release try to install it from PyPI:

```
bin/pip install --no-deps actual-package-name
```

That means a dependency on virtualenv, though everyone should already have that. Best done as a plugin I guess.

Anyway, I'll close this issue now, but at least there are a few more ideas to work on if anyone wants to.

**Comment by mauritsvanrees** [comment]
I said I would close the issue, so I should do that...
