### ISSUE TITLE
`history_file` config option is not documented

### ISSUE THREAD

**Issue by mgedmin** [zestsoftware/zest.releaser#190]
I've a project that uses `NEWS.rst` as the name for the changelog file (for no particular reason, but I don't want to rename it in a bugfix release).  I was looking for a way to make zest.releaser handle this, similar to the existing `python-file-with-version` option.  I was rather surprised to discover, while reading zest.releaser's source code, that there was already an option that does exactly what I want:

``` ini
# setup.cfg
[zest.releaser]
history_file = NEWS.rst
```

It would be very nice if this option and in fact all the setup.cfg options were documented somewhere in http://zestreleaser.readthedocs.io/en/latest/.

**Comment by SmileyChris** [comment]
Looks like it was documented sometime in the last 4 years :P
https://zestreleaser.readthedocs.io/en/latest/options.html#global-options

**Comment by mgedmin** [comment]
This was fixed in 166c93a07733a8c6247f726f0e510359aa6fbc73 in 2018.
