### ISSUE TITLE
Unable to install zest.releaser

### ISSUE THREAD

**Issue by pabo3000** [zestsoftware/zest.releaser#196]
Today I rerunned a buildout and I could not get it to finish. But commenting out zest.releaser helped.

The reason ist that the buildout tries to install docutils = 0.13.1 which is only available as wheel file but not as egg. The dependency comes from readme_renderer which is now downloaded as version 16.0. Indeed readme_renderer 16.0 requires docutils 0.13.1. Pinning readme_renderer to 0.7.0 (the former used distribution) in the buildout.cfg was not possible. I tried to delete it from the buildout cache's eggs and download folder. But no success to convince buildout to use readme_renderer < 16.0.

**Comment by mauritsvanrees** [comment]
Confirmed. :-(  This buildout (without zest.releaser) fails:

```
[buildout]
parts = test
show-picked-versions = true

[test]
recipe = zc.recipe.egg
eggs = readme_renderer

[versions]
zc.buildout= 2.5.3
setuptools = 31.0.0
zc.recipe.egg = 2.0.3

...
$ bin/buildout
...
Got readme-renderer 16.0.
Getting distribution for 'docutils>=0.13.1'.
While:
  Installing test.
  Getting distribution for 'docutils>=0.13.1'.
Error: Couldn't find a distribution for 'docutils>=0.13.1'.
```

Pinning `readme-renderer` *does* help, but you need to spell it with a dash: 

```
readme-renderer = 0.7.0
```

Then buildout finishes and you get `docutils = 0.12`.

**Comment by mauritsvanrees** [comment]
See https://sourceforge.net/p/docutils/bugs/300/ for an issue requesting that docutils upload a standard file next to the wheel.

**Comment by mauritsvanrees** [comment]
A source distribution of docutils has been uploaded, so all is fine again.
