### ISSUE TITLE
zest.releaser.* entry_points do not work

### ISSUE THREAD

**Issue by satyanash** [zestsoftware/zest.releaser#225]
The documentation at https://zestreleaser.readthedocs.io/en/latest/entrypoints.html mentions that custom hooks can be added to the zest releasers by using the `entry_points` kwarg to the `setuptools.setup(..)` function as follows:

```
entry_points={
    'zest.releaser.prereleaser.before': [
        'dosomething = scripts.banner.print_banner',
     ]},
```

But it doesn't work, the option is simply ignored. After digging though the `run_hooks()` function in `utils.py`, it seems that it only reads the hooks from `setup.cfg` and needs to be specified in the following way:

```
## setup.cfg
[zest.releaser]
prereleaser.before = scripts.banner.print_banner
```

Given all this, the documentation that recommends the use of the `entry_points` kwargs seems entirely different from what is happening.

Which of these is the correct way to add custom hooks to the release process?

zest.releaser version: 6.11

**Comment by mauritsvanrees** [comment]
In your `setup.cfg`, you can define hooks specific for this package. They are run first.
After these hooks are run, or if you do not have anything in your `setup.cfg`, all *other* hooks are run.

The other hooks come from your Python path. So if you have for example `check_manifest` installed on your Python path, then during prerelease its hook will be run, checking your `MANIFEST.in` file.

If you have added a hook in the `setup.py` of the package you are developing, then you may need to run `python setup.py egg_info` to make Python aware of your entry point.

Does this help?

**Comment by reinout** [comment]
Those entry points are the regular way. At the end of `run_hooks()`, `run_entry_points()` is called just fine: https://github.com/zestsoftware/zest.releaser/blob/master/zest/releaser/utils.py#L634

The probable cause that it isn't working for you: the entry point code isn't installed together with zest.releaser. Zest.releaser calls `pkg_resources.iter_entry_points()`, so pkg_resources/setuptools must know about your project.

Ah, I see that @mauritsvanrees replied just when I was typing this :-)

**Comment by mauritsvanrees** [comment]
:-)

**Comment by reinout** [comment]
Note to self: see also #235, btw. There are some points that can be documented more clearly.
