### ISSUE TITLE
documentation about entry-points is incomplete

### ISSUE THREAD

**Issue by htgoebel** [zestsoftware/zest.releaser#235]
The documentation about entry-points is incomplete. I found the following topics to be missing:

* Entry-points can also be specified in the `setup.cfg` file like this:
  ```
  [zest.releaser]
  prereleaser.middle =
     my.package.some_module.some_function
     our.package.other_module.other_function
  ```
  The options will be split by white- space and processed in the given order.
* Entry-points given in setup.cfg` will be processed before entry-point defined via installed packages.
* The order entry-point defined via installed packages are processed is not defined.
* Entry-points can change the data, thus one hook can prepare data another one is using. But be aware that *changing* entries in the dict may lead to malfunction.

**Comment by reinout** [comment]
Note to self: TODO :-)

**Comment by reinout** [comment]
Fixed somewhere in the last couple of years: https://zestreleaser.readthedocs.io/en/latest/entrypoints.html#entry-point-specification
