### ISSUE TITLE
Test success depends on external programs' version

### ISSUE THREAD

**Issue by htgoebel** [zestsoftware/zest.releaser#244]
While current master (d75ab3dcd9c80) [passes on travis](https://travis-ci.org/zestsoftware/zest.releaser/builds/300154695), even simple tests fail on my machine:
```
$ export LC_ALL=C
$ bin/test -t zest.releaser/zest/releaser/tests/utils.txt
…
----------------------------------------------------------------------
File "zest/releaser/tests/utils.txt", line 461, in utils.txt
Failed example:
    utils.execute_command('ls some-non-existing-file')
Differences (ndiff with -expected +actual):
    - '\x1b[31mls...'
    + "\x1b[31mls: cannot access 'some-non-existing-file': No such file or directory"
…
```
The test passes if I change the leading single quote in zest/releaser/tests/utils.txt line 462 into a double-quote. So this might be caused by python's repr-quoting (see below).

But the root cause seams to be that the output of `ls` is different due to different versions installed here and at travis. Unfortunately this inhibits me to run the test-suite locally to test my other (more complex) changes.

Proposed solution: Find some other command to run for this test-case.

repr-quoting string depends on whether the string includes single or double quotes:
```
>>> a="aa 'bb' cc"
>>> b="aa bb cc"
>>> c='aa "bb" cc'
>>> a
"aa 'bb' cc"
>>> b
'aa bb cc'
>>> c
'aa "bb" cc'
```

**Comment by htgoebel** [comment]
I prepared a fix for this one. Pull-request coming soon.

**Comment by reinout** [comment]
That's a problem with zest.releaser in general. We want/have to test with external programs like git/hg/svn and are totally dependent on their output being a bit consistent between versions.... I wonder whether a fix for "ls" (which we can of course work around) means you can get the same problem with git/svn etc.

**Comment by htgoebel** [comment]
> means you can get the same problem with git/svn etc.

Yes, bu currently there are not tests effected.

**Comment by htgoebel** [comment]
My proposed change did solve this issue on my machine, made the test fail at travis. I'm afraid, there is no simple solution, except if we provide out own simple `fail` program.

**Comment by reinout** [comment]
A docker for running the tests in could help to get the tests running more reliably.
That would have to be done at the same time as moving away from doctests to pytest or so :-)

**Comment by reinout** [comment]
I'm closing the issue. There's a `Dockerfile` now for those cases where the environment causes trouble.
