### ISSUE TITLE
Don't continue when CHANGES are 'nothing changed yet'

### ISSUE THREAD

**Issue by rvanlaar** [zestsoftware/zest.releaser#26]
Sometimes I forget to add the changes to the CHANGES.rst file and I find out during a release.

A fix would be to detect whether or not the CHANGES.rst has some changes for this release.

**Comment by mauritsvanrees** [comment]
I have created a pull request for this. When the 'Nothing changed yet' line is in the changelog, between the two first headers, we now print a warning and ask 'Are you sure you want to release'. Default answer is no. When answering 'no', we simply print a hint to use the lasttaglog command. People will want to use their favorite editor when adding a changelog entry, and I did not want to handle that.

**Comment by mauritsvanrees** [comment]
Related pull request is merged.
