### ISSUE TITLE
Test upcoming Twine release (1.10.0rc1)?

### ISSUE THREAD

**Issue by brainwane** [zestsoftware/zest.releaser#265]
https://test.pypi.org/project/twine/1.10.0rc1/  is a release candidate for Twine 1.10.0 which I'm planning to release early next week. Please see the [changelog](https://twine.readthedocs.io/en/latest/changelog.html) for detailed notes under "Next feature release".

I believe this is how you test it out on its own  `pip install --upgrade --pre --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple twine` and I want to hear about any problems this new release causes in `zest.releaser`. And if there are some simple tests I can run before a new release to check whether a change in `twine` would break core functionality for you, maybe you could mention that on pypa/twine#314.

Thanks.

**Comment by mauritsvanrees** [comment]
Thanks for the heads up! A quick test shows no problems. Releasing an existing package still works fine.
I'll add a note in the twine issue.

**Comment by brainwane** [comment]
Thanks for the advice and the testing. https://pypi.org/project/twine/1.10.0/ is now out!
