### ISSUE TITLE
Make less-zeroes=no the default

### ISSUE THREAD

**Issue by mauritsvanrees** [zestsoftware/zest.releaser#268]
This is only used in the `bumpversion` command.

Current default is 'yes'. That means with a starting version of `1.2.3`:
- `bumpversion --feature` suggests 1.3
- `bumpversion --breaking` suggests 2.0

I propose to change the default to 'no'. With the same starting version of `1.2.3`:
- `bumpversion --feature` suggests 1.3.0
- `bumpversion --breaking` suggests 2.0.0

That is good for semantic versioning.

I can make the change, but I'd like to know if @reinout agrees. (And others too.)

**Comment by reinout** [comment]
Fine with me. Not too many people will be using the command.

Note that the documentation already mentions "no" as the default :-)

**Comment by mauritsvanrees** [comment]
Oopsie, I looked wrong. You are right, it is the default already. Closing. :-)

**Comment by reinout** [comment]
The doc says "no", but the implementation seems to say "yes".
I didn't even remember this command existed, so I tried it out just now and I'm getting a number like "1.2" and not "1.2.0".

=> I think you should still change something.

**Comment by reinout** [comment]
Hm, default seems to be really "no", too.
Apparently my head isn't made for double negatives like "less_zeroes=False"... I just can't reason effectively about this.

**Comment by mauritsvanrees** [comment]
Tried again, and the default indeed is 'no' and it does what I think it should do.
