### ISSUE TITLE
Add optional args to parse_options

### ISSUE THREAD

**Issue by delijati** [zestsoftware/zest.releaser#278]
It would be nice to have also `args` as an optional argument to `parse_options` https://github.com/zestsoftware/zest.releaser/blob/e41658d04593005b7beb17cde7f58dffba1a257b/zest/releaser/utils.py#L346. Currently i use this to write script tests with pytest.

**Comment by mauritsvanrees** [comment]
What are you trying to do? Write extra tests for `zest.releaser`? Write tests for a package with a `zest.releaser` entry point?

You could create a PR with a test that uses it.

**Comment by reinout** [comment]
Closing the issue. If it is still current, you can re-open it, of course :-)
