### ISSUE TITLE
Choose next version in non interractive mode

### ISSUE THREAD

**Issue by gawel** [zestsoftware/zest.releaser#291]
Hi,

First thanks for this great piece of code. I've discovered zest.releaser years ago and never stopped using it. And I never had any problems! It's just magic.

Today I have many software to release at the same time. And I'd like to decide the new version by myself, without using interactive mode. I've read the code and as I can see there is no way to do that. Am I wrong ?

Ideally, I'd like something like:
```
$ NEXT_VERSION=x.x.x fullrelease --no-input
```

**Comment by reinout** [comment]
What you describe? No, that's not supported as far as I know. There are a couple of options:

- Write your own extension (not very hard) that grabs the version from somewhere (for instance an environment variable).

- What is the version scheme that you're using like? iirc @mauritsvanrees added some options to support automatic `1.3.3` to `1.4` and `1.4.0` version updates, for instance. Perhaps one of those options is what you need.

Btw, the `NEXT_VERSION` env variable trick sounds handy, but it probably means we have to support it for *all* options :-)

**Comment by gawel** [comment]
Passing params to cli via env vars is a popular feature those days :)

But yeah, I didn't notice that you can write extensions. It should feet my needs. I'll dig into it. Thanks!

I'm closing this issue. I can open another one for this env vars feature if you want.

**Comment by hgrecco** [comment]
What do you thing of this for BumpVersion?
```python
class BumpVersionEnv(BumpVersion):

    def __init__(self, *args, **kwargs):
        super().__init__()
        new_version = os.getenv('NEXT_VERSION')
        if new_version:
            self.data['new_version'] = new_version
```

Seems to work as expected but I am not sure that is the right way.

To make it work in fullrelease, would `Prereleaser._grab_version` be the right place to touch?
