### ISSUE TITLE
No way to specify CACERT for uploading to private pypi server

### ISSUE THREAD

**Issue by dkopelove** [zestsoftware/zest.releaser#292]
Hello,

Per the documentation, it's recommended that a user specifies the environment variable TWINE_CERT in order to have twine use a specific ca cert bundle for verification when uploading distributions (src, wheel). 

Unfortunately, zest.releaser is hooking into twine in such a fashion that environmental variables are not evaluated.

This is to request some way of getting this capability of twine pulled out so that it can be specified when calling zest.releaser.

Thanks,
__dan__

**Comment by reinout** [comment]
Could you try again with the latest version of zest.releaser?

We're calling twine on a much higher level now, so there is a big chance that twine gets to do its `TWINE_CERT` thing. We're not calling individual functions anymore, but basically the main `run()` method (or whatever the name).

**Comment by reinout** [comment]
I'm assuming this to be fixed.
