### ISSUE TITLE
Implement PEP-518

### ISSUE THREAD

**Issue by xsc27** [zestsoftware/zest.releaser#295]
Having the ability to use pyproject.toml instead of setup.cfg would be a "nice to have" feature.

**Comment by reinout** [comment]
Yes, agreed.
The code is already pretty flexible where it grabs its settings, so an extra file to look in can be added reasonably simply.

Only thing to watch out for is whether we need an extra dependency to support the .toml syntax. I assume that's OK.

**Comment by graingert** [comment]
usually projects use a `[toml]` extra

**Comment by WouterVH** [comment]
any progress? 
Trying to move my tools-config to pyproject.toml.

**Comment by graingert** [comment]
PEP 621 support would be even better!

**Comment by mauritsvanrees** [comment]
I don't have an immediate need for this, so I am not likely to work on this in the near future.  But if someone wants to make a PR, that would be fine.

Question is which toml parser to use. @graingert mentions [`tomli`](https://pypi.org/project/tomli/), but [`toml`](https://pypi.org/project/toml/) has more stars, and is for example used by `towncrier`, which I use in the `zestreleaser.towncrier` extension, so I would be inclined to use `toml`.

I wonder: what would we do with it? Only use this to read the `zest.releaser` configuration options?

Or do we also for example read and write the version number in `pyproject.toml`? I have not used this file except for towncrier setup, so I don't know if this is supported by one of the dozen PEPs about version numbers...

When we read config options, I would say the following is a good order, where the first file where an option is found, wins:

- command line option 
- `pyproject.toml`
- `setup.cfg`
- `~/.pypirc`

**Comment by WouterVH** [comment]
>> Only use this to read the zest.releaser configuration options?
 Yes.  Newer tools like black only support pyproject.toml and no setup.cfg.
Several tools that read their settings from setup.cfg, have not supported for pyproject.toml, like towncrier, check-manifest, isort,...

**Comment by graingert** [comment]
toml doesn't support toml v1 syntax.  pip is also moving to tomli. https://github.com/pypa/pip/pull/10035

**Comment by regebro** [comment]
In the long run I suppose it needs to support updating the version no matter if it is in setup.cfg or pyproject.toml.

But looking into pyproject.toml at the moment, it seems like setuptools doesn't fully support it. I think the only build project that supports not having a setup.cfg is Poetry?

**Comment by graingert** [comment]
And flit

**Comment by graingert** [comment]
Projects have now for the most part switched to tomli

**Comment by graingert** [comment]
Here's a related issue about pep621  https://github.com/zestsoftware/zest.releaser/issues/373

**Comment by mauritsvanrees** [comment]
`tomli` seems the way to go yes. Even its first version is Python 3 only, but `zest.releaser` currently stil supports 2.7. One way around this, would be to try to import `tomli` and catch an ImportError, and simply only use tomli when it is there. Don't even add it to the dependencies.

A PR in that direction would be welcome. Does anyone want to take this on?
I am happy to help, especially in getting tests to run, because that can be tricky.

Other approach would be to drop Python 2.7 support.
In general, `zest.releaser` could use some more love, cleanup, modernising, and I am currently not giving it that. It is more in bugfix modus, me and @reinout are not actively adding features at the moment. We may want to draw up a plan for the future in a different issue. Some simplification could help.

**Comment by regebro** [comment]
Since Python 2 support ended over one and a half years ago, I fully endorese dropping Python 2 support.

**Comment by graingert** [comment]
I tried making a py2/py3 toml compat lib here https://github.com/graingert/read-toml/blob/default/read_toml/_impl.py#L23

**Comment by graingert** [comment]
I think the way to go about dropping py2 is to cut a release with whatever you've got on the default branch then apply pyupgrade and python_requires with pre-commit.ci

**Comment by mauritsvanrees** [comment]
I have created issue #374 for future plans.

**Comment by mauritsvanrees** [comment]
Version 8.0.0a1 supports writing the version to `pyproject.toml`, so this is a start, and will be enough for some use cases.

But for releasing you still need a `setup.py` for now. Currently `zest.releaser` simply checks if there is a `setup.py`. If it is not there, `zest.releaser` does not create distributions, and does not push to PyPI. That will hopefully be for later in the alpha stage.

**Comment by reinout** [comment]
Fixed in #415
