### ISSUE TITLE
Black's default preference for double quotes dislikes our single quotes

### ISSUE THREAD

**Issue by reinout** [zestsoftware/zest.releaser#301]
I'm experimenting with the "black" (https://black.readthedocs.io/) code formatter and I like it.

One problem: black prefers double quotes, like this:

    version = "0.1"

but zest.releaser writes:

    version = '0.1'

I think we ought to fix this. Using double quotes ourselves would be the easiest solution.
Alternatively we'd have to detect the quoting style.

**Comment by mauritsvanrees** [comment]
I have experimented as well a few weeks or so ago, and like it too.
We can add a `pyproject.toml` file with as contents:

```
[tool.black]
skip-string-normalization = true
```

See comments in this [CMFPlone PR](https://github.com/plone/Products.CMFPlone/pull/2668/files#diff-522adf759addbd3b193c74ca85243f7d). The current Plone style guide recommends single quotes, so in Plone we would need such a config, to not make cleanups by `black` crazy big.

**Comment by reinout** [comment]
@mauritsvanrees: you don't need to release yet, I want to look at #299 right now :-)
