### ISSUE TITLE
Tests at travis fails due to git-svn conflicting with git

### ISSUE THREAD

**Issue by htgoebel** [zestsoftware/zest.releaser#307]
When trying to run tests at travis, these fails to install git-svn with the following error message. See e.g. https://travis-ci.org/zestsoftware/zest.releaser/jobs/482946555
```
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 git-svn : Depends: git (< 1:2.7.4-.)
E: Unable to correct problems, you have held broken packages.
[...]
The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install git-svn" failed and exited with 100 during .
Your build has been stopped.
```

This error does only occur for Python 3.4 and 3.5. I tried fixing this by using `dist: xenial` (see #306) but this will make installation fail even for Python 3.6 and pypy (see https://travis-ci.org/zestsoftware/zest.releaser/builds/482946554)

**Comment by reinout** [comment]
Apt seems to run fine, now.
I guess it was a temporary issue?

**Comment by reinout** [comment]
Assuming it was indeed a temp issue.
