### ISSUE TITLE
Feature: Check if troove classifiers are valid

### ISSUE THREAD

**Issue by jensens** [zestsoftware/zest.releaser#312]
Sometimes there is a typo in a troove classifiers in setup.py/setup.cfg. If so, the release got stuck by a denied upload. It would be very nice to have check here if the classifiers are valid.

**Comment by mauritsvanrees** [comment]
This seems more like something that could be added to an extension, like [`pyroma`](https://github.com/regebro/pyroma) which already does several checks.

**Comment by mauritsvanrees** [comment]
This has been part of `pyroma` for a while now, helped by the `trove-classifiers` package.
