### ISSUE TITLE
make twine upload not fail on 201 status code

### ISSUE THREAD

**Issue by frisi** [zestsoftware/zest.releaser#318]
we're using cloudsmith.io as package index and when uploading python eggs to this index using zest.releaser we get an error message.

reason: zest.releaser checks for the statuscode 200 and cloudsmith sends a 201 "Created" w/o content.
https://github.com/zestsoftware/zest.releaser/blob/6.17.0/zest/releaser/release.py#L218

i'd say zest.releaser should be happy with a 201 code too. what do you think @mauritsvanrees ?

**Comment by reinout** [comment]
Weird? We check requests’ OK statuses. Does it treat 201 as not-ok?

**Comment by frisi** [comment]
@reinout not as not-ok but 200 != 201
https://github.com/kennethreitz/requests/blob/v2.21.0/requests/status_codes.py#L30

**Comment by reinout** [comment]
Ah! I expected it to be a list of 20x codes...

Could you make a small PR so that it accepts 201, too?

**Comment by frisi** [comment]
done @reinout. did not do the necessary setup to get tests running locally though. hope that's ok for you.

**Comment by mauritsvanrees** [comment]
Thanks! Merged and released in version 6.17.1.

**Comment by reinout** [comment]
Thanks, @frisi, for the fix.

**Comment by frisi** [comment]
you're welcome reinout

**Comment by reinout** [comment]
@frisi: there's been some changes in the last week (using a more high level twine function).
Your usecase *should* still work. If something fails for you with the very latest zest.releaser, please notify us :-)

**Comment by frisi** [comment]
thanks for the ping @reinout i'll update to 6.18.1 and see if it works for the next release ;-)
