### ISSUE TITLE
Docs at readthedocs need update

### ISSUE THREAD

**Issue by htgoebel** [zestsoftware/zest.releaser#329]
Please update the dos at zestreleaser.readthedocs.io. Thanks

https://zestreleaser.readthedocs.io/en/latest still is v6.15.4 (according to the [Changelog there](https://zestreleaser.readthedocs.io/en/latest/changelog.html)).

**Comment by reinout** [comment]
You're right! The build hasn't fired since last December!
I manually ran the build. I also clicked around in the configuration: it seems that somehow the github integration got deactivated. I'll do a small commit to test if it works again.

**Comment by reinout** [comment]
It is finally building automatically again.

Thanks for noticing it!
