### ISSUE TITLE
addchangelogentry - ValueError exception when commit messages contain % (percent symbol)

### ISSUE THREAD

**Issue by dkopelove** [zestsoftware/zest.releaser#333]
Steps to Reproduce:

1. pip install zest.releaser
2. run command addchangelogentry "%"
3. observe exception

**Comment by reinout** [comment]
I haven't fixed anything yet, but at least I've added a test in #334 that demonstrates that you're right :-)

**Comment by reinout** [comment]
Ah! The actual changelog behaviour worked fine, but the process crashed when adding the commit message. There's a "%" replacement happening in the commit message handling.

I fixed it by doing a quick `%` => `%%` replacement just for the commit message. And I tested it out on my branch, which worked :-)

**Comment by reinout** [comment]
See https://travis-ci.community/t/cannot-install-git-svn-apt-package/863
Travis installs a much newer git (from a PPA) than is normally present in ubuntu xenial.
git-svn doesn't like that, so it is uninstallable.

**Comment by reinout** [comment]
@dkopelove: it should be fixed in 6.19.1!
Thanks for reporting the problem :-)

**Comment by dkopelove** [comment]
Hi @reinout, I just tried 6.19.1 and it works for me as well. Thank you for the quick turn around.
