### ISSUE TITLE
New colorama release breaks zest.releaser install on Python 3.4. 

### ISSUE THREAD

**Issue by JPTeasdale** [zestsoftware/zest.releaser#342]
Looks like colorama [dropped support for Python 3.4](https://github.com/tartley/colorama/pull/228) which means that `pip install zest.releaser` breaks on python 3.4 as well. 

```
$ pyenv global 3.4.10
$ pip install zest.releaser
Collecting zest.releaser
Collecting colorama (from zest.releaser)
  Using cached https://pypi.uberinternal.com/packages/packages/31/cb/88c908c1be067fb6bacd3d7488ccab1a212533767b951933aac3d22648e2/colorama-0.4.2-py2.py3-none-any.whl
colorama requires Python '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*' but the running Python is 3.4.10

```

**Comment by reinout** [comment]
I guess the simplest solution is to drop support for 3.4 ourselves, too?
(Or at least stop advertising that we support it and stop running the tests for it).
@mauritsvanrees?

**Comment by mauritsvanrees** [comment]
The above error should be fixable by first doing `pip install colorama` with a version constraint that still works.

I am fine with dropping 3.4 support. I am not using it.

Actually: 
- Our [`.travis.yml`](https://github.com/zestsoftware/zest.releaser/blob/master/.travis.yml) does not test it. It tests 2.7, 3.5, 3.6, and pypy.
- Our [`tox.ini`](https://github.com/zestsoftware/zest.releaser/blob/master/tox.ini) tries to test with 3.3+, but I am not using it, might be outdated (could be useful though).
- Our [`setup.py`](https://github.com/zestsoftware/zest.releaser/blob/master/setup.py#L37-L44) claims 2.7 and 3.5+ and PyPy in the classifiers.

So it seems we do not have to do anything (except maybe cleanup `tox.ini`).

For me personally (and the Plone community in general):
- Python 2.7 support is very much wanted, but I suspect this will get trickier, for example latest `setuptools` does not support it. So it is understandable if we drop this at some point this year. But preferably not.
- Python 3.6, 3.7, 3.8 support is needed. Earlier versions not.
- PyPy and PyPy3 are nice to have.

**Comment by reinout** [comment]
I'm closing the issue, we don't support 3.4 anymore :-)
