### ISSUE TITLE
Uploading to multiple servers broke in 6.21

### ISSUE THREAD

**Issue by wosc** [zestsoftware/zest.releaser#357]
AFAICT https://github.com/zestsoftware/zest.releaser/pull/354/files#diff-39d9bdd36a62f86ae3e93a6c833d05daR175 should be `continue` and not `return`, otherwise you can't perform a sequence like "no, yes" if you have multiple servers configured.

**Comment by mauritsvanrees** [comment]
You are right, well spotted!
Let me do a fix.

**Comment by mauritsvanrees** [comment]
Fix released in 6.21.1.

**Comment by wosc** [comment]
Thank you!
