### ISSUE TITLE
Support Markdown file validation under longtest

### ISSUE THREAD

**Issue by nazrulworld** [zestsoftware/zest.releaser#363]
Hi,
I am always used to the tool `longtest` to validate files that are included in setup.py. I am wondering if it is possible to validate Markdown files in the same way.

Thanks

**Comment by mauritsvanrees** [comment]
I hardly ever use this command anymore. Instead I use `restview --long-description`, or `restview CHANGES.rst` if I expect problems in that file. See https://pypi.org/project/restview/

Other options:

- https://pypi.org/project/readme-renderer/
- With recent `twine` versions you can do `python setup.py bdist_wheel && twine check dist/*`, although this does not open a browser for a visual check.

I am not sure how well those handle MarkDown. I am still only using restructured text, though that may change.
