### ISSUE TITLE
Prefixing git tags with a "v"

### ISSUE THREAD

**Issue by keul** [zestsoftware/zest.releaser#375]
It seems that there's a common convention about prefixing git tags with a `v` char.

Tools like npm or cargo-release to this automatically. This is also used by Python libs too ([example](https://github.com/python/cpython/tags).

I'm wondering if zest.releaser can take this train too.

**Comment by mauritsvanrees** [comment]
Hi Luca,
Try the option tag-format.
See https://zestreleaser.readthedocs.io/en/latest/options.html

**Comment by keul** [comment]
Sorry, missed it!
Thanks!
