### ISSUE TITLE
Check version for PEP440

### ISSUE THREAD

**Issue by sweh** [zestsoftware/zest.releaser#381]
Hi,

can zest.releaser check the version string of the to be released package for PEP440 compatibility?

Cheers,
  Sebastian

**Comment by icemac** [comment]
There is https://pypi.org/project/pep440/ maybe it can even be leveraged in an plug-in.

**Comment by mauritsvanrees** [comment]
@sweh I have created PR #383 for this. Could you try this out please?
Note: you must either install `zest.releaser[recommended]` or explicitly install `pep440`.

**Comment by mauritsvanrees** [comment]
Feature is released in 7.0.0a3.
