### ISSUE TITLE
Using zest.release in combination with git-flow

### ISSUE THREAD

**Issue by jjmurre** [zestsoftware/zest.releaser#40]
I want to use zest.releaser together wit git-flow. However, git-flow is writing tags and zest.releaser is also writing tags. So we get sets of unrelated tags. Would there be a way to avoid this situation. Maybe a flag to skip the writing of tags?

**Comment by reinout** [comment]
(Looking through old issues...)

Yep, I still think an extension to deal with git-flow's alternative tag mechanism would be best. Otherwise zest.releaser's code probably gets too if/else-like. I don't know git-flow well enough to see an alternative at the moment (though there might be).

**Comment by htgoebel** [comment]
:+1: for supporting the git-flow workflow. We at PyInstaller are preparing the release on a release-branch, tag the releases on `master` and merge back to develop.

There also is a pure-python implementation of [gitlow](https://pypi.python.org/pypi/gitflow) which eases the process. Creating a `release` branch is as easy as (leaving of error handling):

        gitflow = GitFlow()
        gitflow.start_transaction('create release branch %s' % version)
        branch = gitflow.create('release', version, base)

If you need assistance, feel free to drop me a note.

**Comment by mauritsvanrees** [comment]
This still looks like something that is best done in an extra package that uses the zest.releaser entry points.

**Comment by htgoebel** [comment]
Meanwhile it came to my mind that zesz.releaser can be easily incorperated into the  git flow release process: simply use `prerelease` , `release` and `postrelease` each by it's own.

**Comment by reinout** [comment]
I'm closing this old issue as I'm getting the impression that it can be worked out in git flow itself.

**Comment by mauritsvanrees** [comment]
You can use `egg.releaser` which is a wrapper around `zest.releaser`. Initially created by Thijs in https://github.com/virtualsciences/egg.releaser and forked by me in https://github.com/zestsoftware/egg.releaser

I am sometimes using that for the same client that issue creator @jjmurre may already be using it for. :-) We want to switch away from git flow there though, as most of the team is not used to it. (Me neither, though it works okay.)
