### ISSUE TITLE
testing: the following arguments are required: message

### ISSUE THREAD

**Issue by mtelka** [zestsoftware/zest.releaser#404]
While running tests at OpenIndiana I see this error:
```
Mocking twine.cli.dispatch...
Running tests at level 1
Running zope.testrunner.layer.UnitTests tests:
  Set up zope.testrunner.layer.UnitTests in 0.000 seconds.
  Running:
....usage: __main__.py [-h] [--no-input] [-v] message
__main__.py: error: the following arguments are required: message
..
```

**Comment by mauritsvanrees** [comment]
That is due to these lines:
https://github.com/zestsoftware/zest.releaser/blob/8.0.0a1/zest/releaser/tests/addchangelogentry.txt#L20-L27

We test that we get an error when we call `addchangelogentry` without a message. I don't know a good way to avoid getting this extra output.
