### ISSUE TITLE
Always create wheels, when possible

### ISSUE THREAD

**Issue by mauritsvanrees** [zestsoftware/zest.releaser#406]
It is probably time to always create wheels, also when `setup.cfg` has no `[bdist_wheel]` section and no `[zest.releaser] create-wheel = yes`.

See small discussion with @jensens [here](https://github.com/plone/plone.i18n/pull/50#discussion_r1129310117).

Should be simple enough, just change the logic in [`pypi.create_wheel`](https://github.com/zestsoftware/zest.releaser/blob/8.0.0a1/zest/releaser/pypi.py#L406-L438).  This should return True when the `wheel` package is available (we already check this) and the `[zest.releaser] create-wheel` option is not explicitly set to false.

Can we think of anything against this?
I do a lot of releases, and I always want wheels, next to the source distribution that we always make.

**Comment by reinout** [comment]
Sounds good. I also always want wheels.

**Comment by mauritsvanrees** [comment]
Fixed last month in release 8.0.0a2.
