### ISSUE TITLE
Feature-request: release directly from an url

### ISSUE THREAD

**Issue by WouterVH** [zestsoftware/zest.releaser#46]
Zest.releaser works on a local directory that is checked out from svn/git/hg.

When trying to make people warm to adopt zest.releaser, I received feedback that it would be nice to be able to make releases just by pointing to a trunk-url. This feedback comes from a team that is doing some script-development on Windows behind corporate proxy.

The workflow would be then: they keep working like they do now;  but when code is ready, they can SSH to some linux-box where there is a virtualenv installed and an appropriate .pypirc, and they just do:

  > fullrelease  svn+ssh://user@host/packages/<my_package>/trunk

( the checkout is made in a tmp-folder.)

**Comment by reinout** [comment]
(Old issue, I never reacted on it....)

This isn't something I'd like to add to zest.releaser. It is quite a corner case and a quick shell script on the linux server should be enough.

You could look at checkoutmanager, you can use that to keep a number of git/svn/whatever checkouts up-to-date on the linux server (cronjob) with a quick shell script that runs zest.releaser.

**Comment by WouterVH** [comment]
OK for closing.
