### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by rvanlaar** [zestsoftware/zest.releaser#5]
Please add python3 support :-).

**Comment by mgedmin** [comment]
- z3c.testsetup: lives in ZopeFoundation's ancient SVN repo!  I'll try to convert it to Git.
- martian: IIRC the Pyramid people wrote [Venusian](https://pypi.python.org/pypi/venusian) to do the same thing essentially, only with fewer Zope dependencies and with Python 3 support.  Perhaps it would be possible to switch?  I'm not familiar with either, so I cannot say how compatible or not they are.  What do you use Martian for?
- zc.buildout supports Python 3: you can run python3 bootstrap.py, bin/buildout and get a bin/test

**Comment by mgedmin** [comment]
[z3c.testsetup](https://github.com/zopefoundation/z3c.testsetup) is on GitHub now.  I'm not a PyPI owner of https://pypi.python.org/pypi/z3c.testsetup, which reduces my enthusiasm for porting it to Python 3.  However I see @reinout is a PyPI owner, so can you give me access?  My PyPI username is `mgedmin`.

**Comment by reinout** [comment]
You have access now.

You know, I had completely forgotten I had anything to do with that package :-)

Ideally, I should start setting up more regular tests "one day". So no doctests but regular ones. Perhaps using mock. For now, seeing if z3c.testsetup can be fixed might be quicker.

**Comment by mauritsvanrees** [comment]
We do not use `martian` ourselves. It is a dependency of `z3c.testsetup`.

**Comment by mgedmin** [comment]
I suspect it'd be easier to rewrite the tests not to depend on z3c.testsetup than to port z3c.testsetup and  its dependencies (zope.app.testing.functional is a can of worms).

**Comment by reinout** [comment]
Agreed.

An intermediary step is to start fixing up the python 2.7 code (`__future__` import, `print()`, etc) so that it ought to work with 3.x. And to keep testing with 2.7 for the time being.

With 2.6 out of the way, clean 3.x compatible code shouldn't be too hard (but a lot of work).

**Comment by reinout** [comment]
See https://github.com/zopefoundation/z3c.testsetup/issues/1

I've upped our requirement to z3c.testsetup to the just-released 0.8.4 version.

A little step forward again!

**Comment by reinout** [comment]
Oh wow. I made a separate checkout for python 3 and the poor thing crashes on the `setup.py` already :-)

  Traceback (most recent call last):
    File "/tmp/tmpkfxrx8bw", line 14, in <module>
      exec(compile(f.read(), '/vagrant/zest.releaser3/./setup.py', 'exec'))
    File "/vagrant/zest.releaser3/./setup.py", line 11, in <module>
      long_description = '\n\n'.join([read('README.rst'),
    File "/vagrant/zest.releaser3/./setup.py", line 8, in read
      return unicode(codecs.open(filename, encoding='utf-8').read())
  NameError: name 'unicode' is not defined

**Comment by reinout** [comment]
Ok, I did a quite dirty fix to get it to install: https://github.com/zestsoftware/zest.releaser/commit/552df6675e40e6c4abf6d60681413e1611b1c3a0

The buildout runs, in any case.

Now for the rest of the print functions and so.

And, yes, due to martian the tests don't run.

**Comment by mitchellrj** [comment]
See #97.

**Comment by reinout** [comment]
It'll be in 5.0!
