### ISSUE TITLE
Handling wheels

### ISSUE THREAD

**Issue by hgrecco** [zestsoftware/zest.releaser#55]
It seems that the wheel format is not handled by zest.releaser. It would be nice that if `[bdist_wheel]` is present in `setup.cfg` then
```
python setup.py sdist bdist_wheel upload
```
is called instead of:
```
python setup.py sdist upload
```

**Comment by mauritsvanrees** [comment]
I created a pull request for this. It simply runs the `bdist_wheel` command at the same time as `sdist` when the `wheel` package is available. It does not check `setup.cfg`. I wonder if that is enough initially, or if we should really check if the package has a `setup.cfg` with a `bdist_wheel` section, which could be empty.

The advantage of the simple approach in this pull request is that packages need no changes.

Can we think of existing packages where this is a bad idea?
I am not sure how smart bdist_wheel is about autodiscovering that a correct and sane wheel is created.
Might be safer to check for a `bdist_wheel` entry in setup.cfg. Or possibly add an option for the zest.releaser section.

**Comment by reinout** [comment]
@mauritsvanrees, you started with a `zest.releaser[recommended]` list that includes 'wheel' right now. See #49 where you talk about that recommended list.

**Comment by mauritsvanrees** [comment]
Is on master and will end up in next release (4.0).
