### ISSUE TITLE
Support twine for uploading

### ISSUE THREAD

**Issue by wosc** [zestsoftware/zest.releaser#59]
Since ``setup.py upload`` does not support HTTPS, but [twine](https://pypi.python.org/pypi/twine) does, it would be nice if zest.releaser supported that (at least additionally, but probably even _instead of_ the old method).

**Comment by reinout** [comment]
See #49 in case it is handier to make it an optional dependency.

**Comment by reinout** [comment]
@mgedmin, if you're looking at twine, tackling #20 at the same time is probably very easy?

**Comment by mauritsvanrees** [comment]
I am working on this now. Will create a pull request.

I will note one thing. When a package is not registered to PyPI yet, `twine upload` will fail. You must either manually login to PyPI and register the package, or use `python setup.py register` after all.

See https://github.com/pypa/twine/issues/21

**Comment by reinout** [comment]
This will be fixed in 4.0. You could try master if you wish.
