### ISSUE TITLE
Shouldn't the egg land in the dist directory if not uploading to PyPI?

### ISSUE THREAD

**Issue by djowett** [zestsoftware/zest.releaser#61]
Because the egg didn't go to dist folder (plone/src/product.name/dist) I spent a while looking around for why my egg wasn't built, until I realised that I didn't have my plugins installed.

The egg was built of course - it had just landed in somewhere like:

     /tmp/product.name-0.2.3-Prt03G/gitclone/dist

**Comment by reinout** [comment]
@mauritsvanrees can you take a quick peek at the pull request and merge it once travis is ready with it?
