### ISSUE TITLE
setup.py not always able to update version, so error?

### ISSUE THREAD

**Issue by tomviner** [zestsoftware/zest.releaser#70]
During prerelease, there's a possibility that zest cannot find a way to update your package version number. For example setting your version number in setup.py from a variable set in `mypackage.__init__.py` and forgetting to set python_file_with_version in a setup.cfg.

In this case, your package version number is readable, but not writeable.

This bug hit us today, and raised the question: why would zest continue if it couldn't update your version number?

When it does continue it get's really confused:

1. prerelease updates just the history file, no other file
1. postrelease updates just the history file, to a wrong value! Because it assumes prerelease incremented the package version somewhere.

[Here's `vcs.py:BaseVersionControl._update_version`](https://github.com/zestsoftware/zest.releaser/blob/master/zest/releaser/vcs.py#L175-229) where zest looks for the right place to update a version string. 

I propose that zest raise an exception at the end of that method, if it cannot find a place to update your package version number. Or maybe I'm missing something, is there a deliberate reason zest continues in this case?

I'm happy to write a patch if there's agreement on this.

**Comment by reinout** [comment]
zest.releaser doesn't continue deliberately :-) A version that's not in setup.py or version.txt is mostly a corner case. *That* corner case plus the *additional* corner case of not setting python_file_with_version... Two corner cases in a row is too much for poor zest.releaser.

Your proposal looks ok, though :-) I'd probably add a `version_written = False` line just above https://github.com/zestsoftware/zest.releaser/blob/master/zest/releaser/vcs.py#L213 and set it to True after https://github.com/zestsoftware/zest.releaser/blob/master/zest/releaser/vcs.py#L222 . And an exception if it didn't work. Something like that?

**Comment by tomviner** [comment]
Hi Reinout, granted it's corner case, but thanks for approving the issue :-)

I started off with your suggestion but ended up refactoring a tiny bit. See what you think.

https://github.com/zestsoftware/zest.releaser/pull/71

**Comment by reinout** [comment]
I merged #71, but I made the error logging a bit more elaborate. I'll release later this morning.

**Comment by reinout** [comment]
I released 3.55. Can you check if it works for you?
