### ISSUE TITLE
want_release always True due to pypi config "Safety valve"

### ISSUE THREAD

**Issue by tomviner** [zestsoftware/zest.releaser#74]
The `PypiConfig.want_release` method is designed to read a .pypirc or setup.cfg file and return False if it contains:
```
[zest.releaser]
release = no
```
which is the sole content of my setup.cfg file.

However `PypiConfig._read_configfile` [does a check](https://github.com/zestsoftware/zest.releaser/blob/master/zest/releaser/pypi.py#L176-L179) of validity:

        if (not self.is_old_pypi_config() and
                not self.is_new_pypi_config()):
            # Safety valve
            self.config = None

the `is_old_pypi_config` and `is_new_pypi_config` methods check for `server-login:username` and `distutils:index-servers` respectively in your config file. If you have neither of these `section:keys` you activate the "Safety valve" and get no pypi config.

This means I cannot prevent release (unless I add dummy sections, about servers... that I don't want to release to).

Not quite sure what the solution is. One backwards incompatible idea would be to move the want_release method to SetupConfig, and no longer support `release = no` in your .pypirc file?

So am I doing something wrong, or happy to write a patch, if there's a solution agreed.

**Comment by reinout** [comment]
I'm not sure we really need that safety valve. You could try removing it and see if the tests still run. It was added in https://github.com/zestsoftware/zest.releaser/commit/8bd3e57fa4a6b978fb1641ae5ab5e5c53c740a56 , you might need to adjust one of those tests.

I've never thought about including generic zest.releaser parts in a `.pypirc`, I always treated that as being only for uploading to pypi.

And things like `release = false` is more per-project centric, as everybody that releases it needs to use the same setting, effectively.

But... if it doesn't hurt, I don't mind a fix for this issue :-)

**Comment by tomviner** [comment]
Yeah removing the *safety valve* is the easiest solution, which I have available for PR here: https://github.com/tomviner/zest.releaser/compare/zestsoftware:master...test/remove-safety-valve

I agree that `release = false` belongs in a per project setup.cfg. What's your thoughts on making that the only option though? That would involve moving it to `SetupConfig` I guess.

**Comment by reinout** [comment]
Ok, released with the fix as 3.56.

Can you check if it works for you now?

**Comment by tomviner** [comment]
works great! When I call `release --no-input` my `setup.cfg` is read correctly and sets the default answer to `Check out the tag (for tweaks or pypi/distutils server upload)` to answer no, and thus is able to prevent the whole tag checkout chunk.
 
Many thanks!
