### ISSUE TITLE
Get return codes from subprocesses started by zest.releaser

### ISSUE THREAD

**Issue by mauritsvanrees** [zestsoftware/zest.releaser#84]
In [utils.system](https://github.com/zestsoftware/zest.releaser/blob/3.56/zest/releaser/utils.py#L431) we create subprocesses with a shell. And we look at the return code, but this is always None.  Tested on Mac, maybe Linux and Windows do this differently.

You can test this by adding a working and not working command somewhere in for example prerelease.py:

        print system(utils.setup_py('egg_info'))
        print system(utils.setup_py('My brain hurts'))

If you then `print p.returncode` in the `system` function, it is always None. So with the current code you never actually see an error when this is a Python process: we set `show_stderr` to False and never show the user any error.

Strange is: when you go in with a pdb, the offending subprocess stays alive until the entire zest.releaser program is finished. It is never killed. You can test this by doing `ps | grep python' in another terminal when zest.releaser is asking you a question. When you have no pdb, the subprocess is killed just fine.  In any case the returncode is None.

We may want to do some error handling for commands where we really do want to know what is going wrong.  Something like this:

```
# For system calls, you can determine what to to in case of an error.
# See the 'system' function.
CONTINUE = 0
ASK = 1
ABORT = 2

def system(command, input='', on_error=CONTINUE):
    ...
    if stderr_output and on_error != CONTINUE:
        ... ask or abort.
```

Might give false positives again when a setup.py command prints a few harmless warnings.

**Comment by reinout** [comment]
Something I thought of at the time I was busy suppressing the error output: perhaps start accepting a "-v/--verbose" option that prints, for instance, the error output? Could be used for debugging if some upload fails. Not sure.

**Comment by mauritsvanrees** [comment]
Handled in pull request #90 in a different but seemingly sufficient way.

**Comment by mauritsvanrees** [comment]
Merged to master. Will end up in 4.0 soon.
