### ISSUE TITLE
Abort if ~/.pypirc doesn't exist

### ISSUE THREAD

**Issue by domenkozar** [zestsoftware/zest.releaser#85]
Current zest.releaser skips `upload` if the pypirc is missing. That's very wrong since upload is essential part of `release` step.

Relevant output:

```
WARNING: You must have a properly configured .pypirc file in your home dir to upload an egg.
```

It should abort if the upload command fails.

**Comment by reinout** [comment]
No it should not :-) 

Reason: not everyone uploads to pypi. The 50 internal packages we use at our company are picked up by some cronjob that locally creates the .tgz files and places them in a directory structure.

So unless you want to forbid people from releasing non-python packages (I also use zest.releaser for a documentation project and for a Fortran makefile thingy) and want to enforce uploading to pypi...

**Comment by domenkozar** [comment]
What if it's required if `setup.py` exists? I understand there are many usecases - but having run `release` and not releasing to pypi is also very problematic - since the most important part of the release was just skipped.

**Comment by reinout** [comment]
Like I said, I'm not releasing my internal private projects to pypi. Those projects *do* have a nice and tidy setup.py, though. I'm just making my sdists in a different way for those internal packages (by necessity).

Similarly, sites are often not released to pypi or even some internal pypi clone. But they do often have a setup.py (at least for django, plone, etc). On the server, you check out a tag instead of downloading a pypi release.

So: there are very legitimate reasons for not uploading to pypi, even when there's a setup.py. Does that convince you that it isn't "very problematic"?

**Comment by mauritsvanrees** [comment]
I am with Reinout on this, for the same reasons.

BTW, it would be hard to reliably check. The file might exist, but be empty. It might be improperly formatted. It might have no index-servers specified. Maybe those servers are commented out temporarily to avoid accidental uploading. Username and password might not be specified or may be wrong.

Oh, but maybe look at [plone.releaser](https://github.com/plone/plone.releaser), which uses a few hooks in zest.releaser, one of them to check if the user has pypi access.

**Comment by domenkozar** [comment]
Fair enough.

Reading first sentence of zest.releaser:

``
zest.releaser is collection of command-line programs to help you automate the task of releasing a Python project.
```
zest.releaser has become a lot of things - I'll fork it if I find time someday and adopt it to use a declarative configuration file.

**Comment by domenkozar** [comment]
That being said - don't get me wrong, I understand everyone has different needs :)

**Comment by reinout** [comment]
Releasing is a lot of things. Depending on your co-workers, proper tagging and incrementing versions and adding a new changelog entry can be the **real** challenge :-) That's what I also consider "releasing". Actually **uploading** to pypi can be a part of it. But releasing isn't only uploading.

Anyway, it should be reasonably easy to write a small add-on with an entry point that flatly refuses do anything unless there's a proper pypi :-)
