### ISSUE TITLE
Show colorized output

### ISSUE THREAD

**Issue by mauritsvanrees** [zestsoftware/zest.releaser#86]
Would be nice if we could colorize the output. Especially: make errors red.
I haven't done that before, no idea how easy or hard it is.

**Comment by reinout** [comment]
https://pypi.python.org/pypi/colorama and https://pypi.python.org/pypi/termcolor should help.

I *think* I did something like this lots of years ago, but I don't remember it anymore.

**Comment by mauritsvanrees** [comment]
Looking at PyPI, colorama looks best maintained and most used.

**Comment by mauritsvanrees** [comment]
Merged to master. Will end up in 4.0 soon.
