### ISSUE TITLE
Add optional message to each commit

### ISSUE THREAD

**Issue by mauritsvanrees** [zestsoftware/zest.releaser#87]
On master, commit 5a544e29da1e4a480e32786ebf361beed29e3b33, not released yet, I have added a `setup.cfg` option `ci-skip`. If the value is true, we add `[ci skip]` to the commit messages, for shutting up Travis and maybe Jenkins and others that listen to this.

I am thinking: we could make that more generic. Remove the `ci-skip` option. Add an `extra-message` option. It does exactly what you think it does (I hope).

For skipping the CI, you would no longer have this in `setup.cfg` or `~/.pypirc`:

```
[zest.releaser]
ci-skip = yes
```

but this:

```
[zest.releaser]
extra-message = [ci skip]
```

Does that sound good?

It can easily be used for fun too. I could have added this yesterday when releasing some Plone packages:

```
[zest.releaser]
extra-message =
    Happy World Plone Day!
    [ci skip]
```

;-)

**Comment by reinout** [comment]
Excellent idea! It also saves us a great deal of the-message-needs-to-change bug reports.

**Comment by reinout** [comment]
So... Do it :-)
