### ISSUE TITLE
Use readme for checking package long description

### ISSUE THREAD

**Issue by mauritsvanrees** [zestsoftware/zest.releaser#94]
We could use the [readme package](https://pypi.python.org/pypi/readme) to check the long description of a package before releasing.  Maybe something for the recommended extra. Maybe something for an add-on.

Maybe our `longtest` command can use it too. readme catches a few warnings that longtest ignores.

Examples where I fix such warnings:
- https://github.com/plone/plone.app.theming/commit/537d58e9cf905ae0cfd5587865c46dce1358b956
- https://github.com/plone/plone.app.theming/commit/09223984d2ed2a886c94bcbe657f2a52ae5ecaad

**Comment by reinout** [comment]
I haven't looked at the readme package yet. But in any case: moving docutils into the recommended extra list is probably a good idea?

**Comment by reinout** [comment]
There's code that adds the readme package in the HUGE HUGE HUGE python 3 patch: https://github.com/isotoma/zest.releaser/commit/ec57c69ff16a3672d0f2775851fb1942c423dd84

**Comment by reinout** [comment]
See #103 and especially the fixes in #104

**Comment by reinout** [comment]
Done
