### ISSUE TITLE
Fix cyclic imports via choose.py

### ISSUE THREAD

**Issue by reinout** [zestsoftware/zest.releaser#95]
See https://landscape.io/github/zestsoftware/zest.releaser/80/modules/zest/releaser/baserelease.py

That loooks pretty non-van-rees-like-regular-behaviour to me :-)

**Comment by mauritsvanrees** [comment]
Might be false positives. Might be fixable.

Seems this is in `utils.py` in `prepare_documentation_entrypoint` where we import prerelease, release and postrelease. We do it in this function exactly to prevent circular imports.

Maybe move this function somewhere else, to a separate file?

**Comment by mauritsvanrees** [comment]
Pull request was merged, so this is fixed.
